// packages/react/src/components/Dropdown.tsx
import {
  useRef,
  useEffect,
  useLayoutEffect,
  type DragEvent,
  type KeyboardEvent,
  type ReactNode,
} from 'react'

export interface DropdownProps {
  trigger: ReactNode
  children: ReactNode
  open: boolean
  setOpen: (open: boolean) => void
  // Bound to the panel itself (not per-row) so a drag-and-drop reorder list inside can resolve
  // a drop that lands past its last row / in unrelated dead space — see the Sort/Group/Columns
  // dropdown drag handlers in DataTableView.tsx.
  onDragOver?: (e: DragEvent<HTMLDivElement>) => void
  onDrop?: (e: DragEvent<HTMLDivElement>) => void
  // Rendered as a sibling of the trigger — inside the same outside-click boundary as the trigger
  // and panel (so clicking it doesn't spuriously close the dropdown via the "click outside"
  // handler below), but outside the trigger's own onClick toggle (so it never opens/closes the
  // dropdown itself). Used for the Sort/Group/Filter toolbar's adjoining × clear button (see
  // DataTableView.tsx), visually merged into one pill with the trigger via shared CSS.
  extraTrigger?: ReactNode
}

// The panel's roving Up/Down/Home/End nav (see the keydown handler below) and its focus-on-open
// behavior (see the layout effect below) both need the same "ordered list of this panel's own
// focusable row/search elements" — shared here so the two stay in sync. `data-dd-search` marks a
// dropdown's own column-search input (Columns/Sort/Group's addable list/Filter's left pane, see
// DataTableView.tsx); `data-dd-row` marks every other row this nav should reach (a column
// checkbox row, a Sort/Group active or addable entry, a Filter column-selector button). This is
// deliberately generic — Dropdown has no idea which concrete dropdown it's rendering, only that
// its children may carry these two markers.
const DD_NAV_SELECTOR = 'input[data-dd-search], [data-dd-row]'

function ddFocusableFor(el: HTMLElement): HTMLElement | null {
  return el.matches('input, button, [tabindex]')
    ? el
    : el.querySelector<HTMLElement>('input, button, [tabindex]')
}

function ddNavFocusables(panel: HTMLElement): HTMLElement[] {
  return Array.from(panel.querySelectorAll<HTMLElement>(DD_NAV_SELECTOR))
    .map(ddFocusableFor)
    .filter((el): el is HTMLElement => el !== null)
}

export function Dropdown({
  trigger,
  children,
  open,
  setOpen,
  onDragOver,
  onDrop,
  extraTrigger,
}: DropdownProps) {
  const ref = useRef<HTMLDivElement>(null)
  const panelRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [setOpen])

  // The panel unmounts entirely when closed, so each open is a fresh DOM node at its natural
  // (unclamped) position — this mutates that node's style directly rather than going through
  // React state (which would need a setState-in-effect, flagged as a cascading-render risk by
  // this project's eslint-plugin-react-hooks config). A translateX offset is used for the
  // horizontal case instead of flipping left:0 -> right:0, since the overflow is relative to
  // the viewport, not to the trigger (see vanilla's Dropdown clamp for the reasoning).
  useLayoutEffect(() => {
    if (!open) return
    const panel = panelRef.current
    if (!panel) return
    const margin = 8
    const rect = panel.getBoundingClientRect()
    let dx = 0
    if (rect.right > window.innerWidth - margin) dx = window.innerWidth - margin - rect.right
    if (rect.left + dx < margin) dx = margin - rect.left
    if (dx !== 0) panel.style.transform = `translateX(${dx}px)`
    if (rect.bottom > window.innerHeight - margin) {
      panel.style.top = 'auto'
      panel.style.marginTop = '0'
      panel.style.bottom = '100%'
      panel.style.marginBottom = '4px'
    }
    // Opening a dropdown should hand it focus immediately — its own search box if it has one
    // (preferred regardless of where it sits in the DOM, e.g. Sort/Group's search box renders
    // *after* the active-entries section but is still the preferred landing spot, matching
    // vanilla's focusFirstInDropdown), else the first row (e.g. Sort with every column already
    // sorted has no addable section and therefore no search box).
    const search = panel.querySelector<HTMLElement>('input[data-dd-search]')
    if (search) search.focus()
    else ddNavFocusables(panel)[0]?.focus()
  }, [open])

  // Roving Up/Down/Home/End/Escape navigation across this panel's own search box + rows — see
  // DD_NAV_SELECTOR above. A distinct concern from any Alt+↑/↓ reorder or Enter/Space toggle a
  // row itself implements (see the Sort/Group active rows in DataTableView.tsx): those don't
  // stopPropagation, so this still runs after them via bubbling, but its own `!e.altKey` guard
  // keeps it from ever acting on their modifier combo. Scoped to elements this panel actually
  // recognizes (`focusables.indexOf(active) !== -1`) so it never interferes with unrelated
  // controls elsewhere in the panel (e.g. the Filter dropdown's right-hand detail pane, which
  // implements its own nav — see handleFilterPanelKeyDown in DataTableView.tsx — including native
  // Left/Right/Up/Down/Home/End on its own range inputs/slider that must keep working unmolested).
  const handlePanelKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    if (e.altKey) return
    if (e.key === 'Escape') {
      e.preventDefault()
      setOpen(false)
      ref.current?.querySelector<HTMLElement>('button')?.focus()
      return
    }
    if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp' && e.key !== 'Home' && e.key !== 'End') return
    const panel = panelRef.current
    if (!panel) return
    const focusables = ddNavFocusables(panel)
    const rowFocusables = focusables.filter((el) => !el.matches('input[data-dd-search]'))
    const active = document.activeElement as HTMLElement | null
    if (!active || focusables.indexOf(active) === -1) return
    if (e.key === 'Home' || e.key === 'End') {
      if (rowFocusables.length === 0) return
      e.preventDefault()
      ;(e.key === 'Home' ? rowFocusables[0] : rowFocusables[rowFocusables.length - 1]).focus()
      return
    }
    const idx = focusables.indexOf(active)
    const nextIdx = e.key === 'ArrowDown' ? idx + 1 : idx - 1
    if (nextIdx < 0 || nextIdx >= focusables.length) return
    e.preventDefault()
    focusables[nextIdx].focus()
  }

  return (
    <div ref={ref} style={{ position: 'relative', display: 'inline-flex' }}>
      <div onClick={() => setOpen(!open)}>{trigger}</div>
      {extraTrigger}
      {open && (
        <div
          ref={panelRef}
          onDragOver={onDragOver}
          onDrop={onDrop}
          onKeyDown={handlePanelKeyDown}
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            zIndex: 100,
            marginTop: 4,
            background: 'var(--color-background-primary)',
            border: '0.5px solid var(--color-border-secondary)',
            borderRadius: 8,
            boxShadow: '0 4px 16px rgba(0,0,0,0.10)',
            minWidth: 220,
            maxHeight: 420,
            overflowY: 'auto',
            padding: '4px 0',
          }}
        >
          {children}
        </div>
      )}
    </div>
  )
}

// packages/vanilla/src/components/Dropdown.tsx
import { type JSX, Show, createSignal, onCleanup, onMount } from 'solid-js'

interface DropdownProps {
  isOpen: boolean
  onToggle: () => void
  onClose: () => void
  trigger: JSX.Element
  /** Rendered as a sibling of `trigger`, inside the same outside-click boundary — see the
   * toolbar's per-dropdown × clear buttons (CLAUDE.md's "Toolbar clear buttons"). */
  extraTrigger?: JSX.Element
  children: JSX.Element
}

// Generic dropdown shell shared by Columns/Sort/Group/Filter — mirrors react/components/Dropdown.tsx
// and vue/components/Dropdown.vue's role. Handles: open/close, outside-click-to-close, Escape-to-close,
// and viewport clamping (translateX so a wide panel opened near the right edge doesn't render
// off-screen — see CLAUDE.md's "Dropdown viewport clamping").
//
// Simplification vs. the fuller documented behavior (noted here rather than silently dropped):
// the generic column-search roving Up/Down/Home/End keyboard nav described in "Dropdown column
// search and keyboard navigation" is not implemented in this first pass — panel contents are
// still fully reachable via native Tab order (every row is a real <button>/focusable element),
// just not via dedicated arrow-key roving yet. Flagged as a follow-up once the full view is
// assembled and there's a concrete set of panels to validate it against.
export function Dropdown(props: DropdownProps) {
  let wrapRef: HTMLDivElement | undefined
  let panelRef: HTMLDivElement | undefined
  const [flipUp, setFlipUp] = createSignal(false)
  const [translateX, setTranslateX] = createSignal(0)

  function handleDocClick(e: MouseEvent): void {
    // Every Columns/Sort/Group/Filter dropdown mounts its own Dropdown instance simultaneously,
    // each with its own document-level capture listener. Without this `props.isOpen` guard, a
    // click anywhere inside the *currently open* dropdown's own panel would still be treated as
    // "outside" by every *other*, currently-closed dropdown's listener — and since all four share
    // one `openDropdown` signal, any of their `onClose()` calls closes whichever one actually is
    // open, immediately after the click reaches its real target. (Found via the full
    // createDataTable integration tests: it never surfaced in a single-component test, since
    // there's no sibling dropdown there to falsely fire.)
    if (!props.isOpen) return
    if (wrapRef && !wrapRef.contains(e.target as Node)) props.onClose()
  }
  function handleKeyDown(e: KeyboardEvent): void {
    if (e.key === 'Escape') {
      e.stopPropagation()
      props.onClose()
    }
  }
  onMount(() => {
    document.addEventListener('click', handleDocClick, true)
    onCleanup(() => document.removeEventListener('click', handleDocClick, true))
  })

  function clampToViewport(el: HTMLDivElement): void {
    const rect = el.getBoundingClientRect()
    const margin = 8
    let dx = 0
    if (rect.right > window.innerWidth - margin) dx = window.innerWidth - margin - rect.right
    if (rect.left + dx < margin) dx = margin - rect.left
    setTranslateX(dx)
    setFlipUp(rect.bottom > window.innerHeight - margin)
  }

  return (
    <div class="dt-dd-wrap" ref={wrapRef} onKeyDown={handleKeyDown}>
      <span style={{ display: 'inline-flex' }}>
        {props.trigger}
        {props.extraTrigger}
      </span>
      <Show when={props.isOpen}>
        <div
          class={`dt-dd${flipUp() ? ' dt-dd--up' : ''}`}
          ref={(el) => {
            panelRef = el
            // Measure after the panel's real content is laid out — a ref callback fires at
            // insertion time, before the browser has computed layout for this frame.
            queueMicrotask(() => panelRef && clampToViewport(panelRef))
          }}
          style={{ transform: translateX() ? `translateX(${translateX()}px)` : undefined }}
        >
          {props.children}
        </div>
      </Show>
    </div>
  )
}
