// packages/vue/src/components/RangeSlider.vue
<script setup lang="ts">
// The "2 inputs + a slider" range control's slider half — two overlapping native
// <input type="range"> thumbs sharing one visual track (only the thumb itself is a hit target,
// via the scoped ::-webkit-slider-thumb/::-moz-range-thumb rules below, so grabbing either one
// works regardless of z-order) plus a colored fill between them. `min`/`max` are the column's
// actual data bounds (see computeValueBounds); `low`/`high` are already sorted by the caller.
// `change` always receives already-sorted (low, high) — dragging one thumb past the other just
// swaps their visual roles on the next render rather than needing cross-clamping, the standard
// behavior for this two-native-inputs trick.
defineProps<{
  min: number
  max: number
  low: number
  high: number
  step: number | 'any'
  minLabel: string
  maxLabel: string
}>()

const emit = defineEmits<{
  change: [low: number, high: number]
}>()

function handleThumb(raw: number, other: number): void {
  emit('change', Math.min(raw, other), Math.max(raw, other))
}
</script>

<template>
  <div class="dt__range-slider">
    <div class="dt__range-slider-track" />
    <div
      class="dt__range-slider-fill"
      :style="{
        left: `${((low - min) / (max - min)) * 100}%`,
        right: `${100 - ((high - min) / (max - min)) * 100}%`,
      }"
    />
    <input
      type="range"
      class="dt__range-slider-thumb"
      :min="min"
      :max="max"
      :step="step"
      :value="low"
      :aria-label="minLabel"
      @input="handleThumb(Number(($event.target as HTMLInputElement).value), high)"
    />
    <input
      type="range"
      class="dt__range-slider-thumb"
      :min="min"
      :max="max"
      :step="step"
      :value="high"
      :aria-label="maxLabel"
      @input="handleThumb(Number(($event.target as HTMLInputElement).value), low)"
    />
  </div>
</template>

<style scoped>
.dt__range-slider {
  position: relative;
  height: 22px;
  margin: 8px 2px 2px;
}
.dt__range-slider-track {
  position: absolute;
  top: 50%;
  left: 7px;
  right: 7px;
  height: 4px;
  margin-top: -2px;
  border-radius: 2px;
  background: var(--color-border-secondary);
}
.dt__range-slider-fill {
  position: absolute;
  top: 50%;
  height: 4px;
  margin-top: -2px;
  border-radius: 2px;
  background: var(--color-text-info);
}
.dt__range-slider-thumb {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  width: 100%;
  height: 22px;
  margin: 0;
  padding: 0;
  background: transparent;
  border: none;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  pointer-events: none;
}
.dt__range-slider-thumb::-webkit-slider-runnable-track {
  background: transparent;
}
.dt__range-slider-thumb::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  pointer-events: auto;
  width: 14px;
  height: 14px;
  margin-top: 4px;
  border-radius: 50%;
  background: var(--color-text-info);
  border: 2px solid var(--color-background-primary);
  box-shadow: 0 0 0 1px var(--color-border-info);
  cursor: pointer;
}
.dt__range-slider-thumb::-moz-range-track {
  background: transparent;
  border: none;
}
.dt__range-slider-thumb::-moz-range-thumb {
  pointer-events: auto;
  width: 14px;
  height: 14px;
  border-radius: 50%;
  background: var(--color-text-info);
  border: 2px solid var(--color-background-primary);
  box-shadow: 0 0 0 1px var(--color-border-info);
  cursor: pointer;
}
</style>

// packages/vanilla/src/components/RangeSlider.tsx
import { Show } from 'solid-js'
import type { RangeFilter } from '@vates/data-table-core'
import type { ColumnDef } from '../types'

interface RangeSliderProps<TRow extends object> {
  col: ColumnDef<TRow>
  rangeFilter: RangeFilter | undefined
  bounds: { min: number; max: number } | null
  onCommit: (min: string, max: string) => void
}

function formatRangeBound<TRow extends object>(n: number, col: ColumnDef<TRow>): string {
  return col.type === 'date' ? new Date(n).toISOString().slice(0, 10) : String(n)
}

// "2 inputs + a slider" range control (see CLAUDE.md's "type: 'number'/'type: 'date' range
// filters get a slider") — two overlapping native <input type="range"> thumbs sharing one visual
// track (styles.ts makes only the thumb itself a hit target). Both thumbs share one onInput:
// the actual applied min/max is always Math.min/Math.max of both thumbs' live values, so dragging
// one thumb past the other just swaps their visual roles instead of needing cross-clamping.
//
// Unlike the old vanilla code (which had to split range-slider handling across `input`/`change`
// events specifically to avoid destroying the dragged thumb mid-drag via a full innerHTML
// rebuild), Solid's controlled inputs update the same DOM node in place — dragging is never
// disturbed by a state-driven re-render, so every tick can commit directly. Same simplification
// React/Vue's own equivalents already got for free.
//
// The "no bounds" (or degenerate min>=max) case is a reactive <Show>, not an early `return null`
// in the setup body — this component's props can change identity (switching the active filter
// column between two number/date columns) while the JSX position that renders it stays the same,
// so Solid keeps this same instance mounted rather than remounting a fresh one; an early return
// evaluated once at setup time would freeze on whatever the first column's bounds happened to be.
export function RangeSlider<TRow extends object>(props: RangeSliderProps<TRow>) {
  const isDate = () => props.col.type === 'date'
  const toNum = (v: string) => (isDate() ? new Date(v).getTime() : Number(v))
  const low = () =>
    props.rangeFilter?.min ? toNum(props.rangeFilter.min) : (props.bounds?.min ?? 0)
  const high = () =>
    props.rangeFilter?.max ? toNum(props.rangeFilter.max) : (props.bounds?.max ?? 0)
  const lo = () => Math.min(low(), high())
  const hi = () => Math.max(low(), high())
  const step = () => (isDate() ? String(24 * 60 * 60 * 1000) : 'any')
  const pctLo = () =>
    props.bounds ? ((lo() - props.bounds.min) / (props.bounds.max - props.bounds.min)) * 100 : 0
  const pctHi = () =>
    props.bounds ? ((hi() - props.bounds.min) / (props.bounds.max - props.bounds.min)) * 100 : 0

  let thumbA: HTMLInputElement | undefined
  let thumbB: HTMLInputElement | undefined
  function handleInput(): void {
    // Both thumbs are read fresh from the DOM (not from Solid state) so a drag on either one is
    // reflected immediately regardless of which one moved.
    const vals = [thumbA, thumbB]
      .filter((t): t is HTMLInputElement => !!t)
      .map((t) => Number(t.value))
    const newLo = Math.min(...vals)
    const newHi = Math.max(...vals)
    props.onCommit(formatRangeBound(newLo, props.col), formatRangeBound(newHi, props.col))
  }

  return (
    <Show when={props.bounds && props.bounds.min < props.bounds.max}>
      <div class="dt-range-slider">
        <div class="dt-range-slider-track" />
        <div
          class="dt-range-slider-fill"
          style={{ left: `${pctLo()}%`, right: `${100 - pctHi()}%` }}
        />
        <input
          type="range"
          class="dt-range-slider-thumb"
          min={props.bounds?.min}
          max={props.bounds?.max}
          step={step()}
          value={lo()}
          aria-label="min"
          ref={thumbA}
          onInput={handleInput}
        />
        <input
          type="range"
          class="dt-range-slider-thumb"
          min={props.bounds?.min}
          max={props.bounds?.max}
          step={step()}
          value={hi()}
          aria-label="max"
          ref={thumbB}
          onInput={handleInput}
        />
      </div>
    </Show>
  )
}
