// packages/vue/src/components/CategorySubmenu.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  computeSubmenuPosition,
  ddNavFocusables,
  viewportWidth,
} from '@vates/data-table-core/internal'

// Hover-intent delays (see docs/columns.md's "Column categories") — a native OS/app-menu-style flyout
// opens on hover once its parent menu is already open. OPEN_DELAY avoids a flicker-open while the
// pointer merely sweeps across a category row on its way to something else; CLOSE_DELAY is
// longer, giving the pointer room to travel diagonally from the trigger into the submenu itself
// without the gap between them (however narrow) closing it prematurely. Click still opens/closes
// immediately (no delay), as do ArrowRight/Enter/Escape — matches Solid/React's identical
// component.
const OPEN_DELAY = 100
const CLOSE_DELAY = 250

// Vue's dropdown markup uses class-based row selectors, not the `data-dd-row` attribute React/
// Solid render (see DD_NAV_SELECTOR's own doc comment, core) — mirrors Dropdown.vue's own
// `DEFAULT_ROW_SELECTOR` (only the `button.dt__dd-item--clickable` part is reachable from inside
// a category submenu; the other row kinds it also matches never appear here).
const SUBMENU_ROW_SELECTOR = 'button.dt__dd-item--clickable'

// Positioned with `position: fixed` at viewport coordinates computed from the trigger's own rect
// (`computeSubmenuPosition`, core), but rendered as a plain sibling of the trigger — NOT
// teleported to `document.body`, and NOT `position: absolute` either. Solid's own first version
// used `position: absolute` and hit a real bug: `.dt__dd`'s `overflow-y: auto` (see Dropdown.vue's
// panel style) means an absolutely positioned descendant that overflows a scrollable ancestor
// horizontally still grows that ancestor's own scrollable region even though it's out of normal
// flow — clipping the flyout and adding a spurious horizontal scrollbar to the whole panel. A
// `<Teleport to="body">` was tried next and does dodge that, but comes with a real cost: a
// teleported node is no longer a DOM descendant of whatever ancestor a consumer scopes theme CSS
// custom properties to (if that ancestor is narrower than `<body>`), so the submenu silently falls
// back to the library's baked-in default colors instead of inheriting the consumer's theme
// (GitHub issue #23). `position: fixed` alone turns out to solve the original overflow problem on
// its own, with no teleport needed: a fixed element's containing block is the *viewport*, not any
// scrolling ancestor, unless that ancestor sets `transform`/`filter`/`perspective`/
// `will-change: transform` (none of `.dt__dd`'s chrome does) — so a fixed submenu never
// contributes to `.dt__dd`'s scrollable area in the first place, teleport or not.
//
// Because the submenu is a real DOM descendant of the panel again, its rows *are* reachable by
// Dropdown.vue's own generic panel-wide roving nav — which is exactly why that nav explicitly
// excludes anything inside `[data-category-submenu]` (see its own comment): `onSubmenuKeydown`
// below is still what should drive Up/Down/Home/End while the submenu is open, not the panel's.
// It calls `stopPropagation()` so Dropdown.vue's own panel-level handler never double-handles the
// same keydown.

const props = defineProps<{
  name: string
  // Controlled, not self-managed: the parent (Sort/Group/Columns' own DataTableView.vue block)
  // owns one shared "which category is open" value across every CategorySubmenu in its list, so
  // opening one always closes any other that was open in the same dropdown.
  isOpen: boolean
  /** Names the flyout as a group (the header menu's filter controls) */
  groupLabel?: string
  /** Extra class on the flyout */
  submenuClass?: string
}>()
// `icon`: shown before `name` (the header menu's Filter item)
defineSlots<{ default?: () => unknown; icon?: () => unknown }>()
const emit = defineEmits<{ open: []; close: [] }>()

const left = ref(0)
const top = ref(0)
const triggerRef = ref<HTMLButtonElement | null>(null)
const submenuRef = ref<HTMLDivElement | null>(null)
let openTimer: ReturnType<typeof setTimeout> | undefined
let closeTimer: ReturnType<typeof setTimeout> | undefined

function cancelOpen(): void {
  if (openTimer) {
    clearTimeout(openTimer)
    openTimer = undefined
  }
}
function cancelClose(): void {
  if (closeTimer) {
    clearTimeout(closeTimer)
    closeTimer = undefined
  }
}

function focusFirstRow(): void {
  queueMicrotask(() => {
    const el = submenuRef.value
    if (!el) return
    // A flyout without rows (the header menu's filter pane) starts on its first text field
    ;(
      ddNavFocusables(el, SUBMENU_ROW_SELECTOR)[0] ??
      el.querySelector<HTMLElement>('input[type=text]') ??
      el.querySelector<HTMLElement>('input, button')
    )?.focus()
  })
}
function openNow(focusFirst: boolean): void {
  cancelOpen()
  cancelClose()
  if (!props.isOpen) {
    if (triggerRef.value) {
      // Initial guess (right of the trigger, top-aligned) — corrected by the position-fixing
      // watcher below once the submenu's real size is known. Avoids a 0,0-positioned flash before
      // that measurement lands.
      const rect = triggerRef.value.getBoundingClientRect()
      left.value = rect.right
      top.value = rect.top
    }
    emit('open')
  }
  if (focusFirst) focusFirstRow()
}
function closeNow(focusTrigger: boolean): void {
  cancelOpen()
  cancelClose()
  if (props.isOpen) emit('close')
  if (focusTrigger) triggerRef.value?.focus()
}
function scheduleOpen(): void {
  cancelClose()
  if (props.isOpen || openTimer) return
  openTimer = setTimeout(() => {
    openTimer = undefined
    openNow(false)
  }, OPEN_DELAY)
}
function scheduleClose(): void {
  cancelOpen()
  if (closeTimer) return
  closeTimer = setTimeout(() => {
    closeTimer = undefined
    closeNow(false)
  }, CLOSE_DELAY)
}

// Corrects the initial guess above once the submenu's real size is known — a ref callback fires
// before this div's own children (the slotted rows) are appended, so the measurement needs to
// wait a tick, same as Dropdown.vue's own viewport-clamp watcher.
function onSubmenuMounted(el: Element | null): void {
  submenuRef.value = el as HTMLDivElement | null
  if (!submenuRef.value) return
  queueMicrotask(() => {
    if (!submenuRef.value || !triggerRef.value) return
    const triggerRect = triggerRef.value.getBoundingClientRect()
    const rect = submenuRef.value.getBoundingClientRect()
    const pos = computeSubmenuPosition(
      triggerRect,
      { width: rect.width, height: rect.height },
      viewportWidth(),
      window.innerHeight,
    )
    left.value = pos.left
    top.value = pos.top
  })
}

function onSubmenuKeydown(e: KeyboardEvent): void {
  // ← in a text field moves its caret instead
  const inText = e.target instanceof HTMLInputElement && e.target.type !== 'checkbox'
  if (e.key === 'Escape' || (e.key === 'ArrowLeft' && !inText)) {
    e.preventDefault()
    e.stopPropagation()
    closeNow(true)
    return
  }
  if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp' && e.key !== 'Home' && e.key !== 'End') return
  if (!submenuRef.value) return
  const focusables = ddNavFocusables(submenuRef.value, SUBMENU_ROW_SELECTOR)
  const active = document.activeElement as HTMLElement | null
  const idx = active ? focusables.indexOf(active) : -1
  if (idx === -1) return
  e.stopPropagation()
  if (e.key === 'Home' || e.key === 'End') {
    e.preventDefault()
    ;(e.key === 'Home' ? focusables[0] : focusables[focusables.length - 1])?.focus()
    return
  }
  const nextIdx = e.key === 'ArrowDown' ? idx + 1 : idx - 1
  if (nextIdx < 0 || nextIdx >= focusables.length) return
  e.preventDefault()
  focusables[nextIdx]?.focus()
}

defineExpose({ triggerRef })
</script>

<template>
  <div class="dt__dd-category">
    <button
      ref="triggerRef"
      type="button"
      class="dt__dd-item dt__dd-item--clickable dt__dd-category-trigger"
      data-dd-row
      :data-category-name="props.name"
      :aria-expanded="props.isOpen"
      @mouseenter="scheduleOpen"
      @mouseleave="scheduleClose"
      @click="props.isOpen ? closeNow(false) : openNow(true)"
      @keydown="
        (e: KeyboardEvent) => {
          if (e.key === 'ArrowRight' && !props.isOpen) {
            e.preventDefault()
            openNow(true)
          }
        }
      "
    >
      <slot name="icon" />
      <span class="dt__dd-category-label">{{ props.name }}</span>
      <span class="dt__dd-category-arrow">▸</span>
    </button>
    <div
      v-if="props.isOpen"
      :ref="(el) => onSubmenuMounted(el as Element | null)"
      :class="['dt__dd-submenu', props.submenuClass]"
      data-category-submenu
      :role="props.groupLabel ? 'group' : undefined"
      :aria-label="props.groupLabel"
      :style="{ position: 'fixed', left: `${left}px`, top: `${top}px` }"
      @mouseenter="cancelClose"
      @mouseleave="scheduleClose"
      @keydown="onSubmenuKeydown"
    >
      <slot />
    </div>
  </div>
</template>

<style scoped>
/* Vue's scoped CSS only stamps a component's own `data-v-*` scope id onto elements literally
   written in *its own* template — the trigger button/submenu div below are this component's own
   template (unlike the addable-column buttons rendered through `<slot />`, which stay stamped
   with DataTableView.vue's scope id and pick up its `.dt__dd-item`/`.dt__dd-item--clickable`
   rules there for free). So the base item look needs its own copy here too, mirroring
   ToolbarBtn.vue's same self-contained-styling convention for a child component that needs a
   shared `dt__`-prefixed look. */
.dt__dd-category {
  position: relative;
}
.dt__dd-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 7px 14px;
  font-size: 13px;
  color: var(--color-text-primary);
  border: none;
  background: none;
  font-family: inherit;
  text-align: left;
  margin: 0;
  width: 100%;
  box-sizing: border-box;
}
.dt__dd-item--clickable {
  cursor: pointer;
}
.dt__dd-item--clickable:hover,
.dt__dd-item--clickable:focus {
  background: var(--color-background-secondary);
}
.dt__dd-category-trigger {
  justify-content: space-between;
}
.dt__dd-category-label {
  flex: 1;
}
.dt__dd-category-arrow {
  flex-shrink: 0;
  font-size: 10px;
  color: var(--color-text-tertiary);
}
.dt__dd-submenu {
  z-index: 101;
  background: var(--color-background-primary);
  border: 0.5px solid var(--color-border-secondary);
  border-radius: 8px;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
  min-width: 160px;
  max-height: 320px;
  overflow-y: auto;
  padding: 4px 0;
}
</style>

// packages/react/src/components/CategorySubmenu.tsx
import {
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent,
  type ReactNode,
} from 'react'
import {
  computeSubmenuPosition,
  ddNavFocusables,
  viewportWidth,
} from '@vates/data-table-core/internal'

// Hover-intent delays (see docs/columns.md's "Column categories") — a native OS/app-menu-style flyout
// opens on hover once its parent menu is already open. OPEN_DELAY avoids a flicker-open while the
// pointer merely sweeps across a category row on its way to something else; CLOSE_DELAY is
// longer, giving the pointer room to travel diagonally from the trigger into the submenu itself
// without the gap between them (however narrow) closing it prematurely. Click still opens/closes
// immediately (no delay), as do ArrowRight/Enter/Escape — matches Solid's identical component.
const OPEN_DELAY = 100
const CLOSE_DELAY = 250

export interface CategorySubmenuProps {
  name: string
  // Controlled, not self-managed: the parent (Sort/Group's own DataTableView.tsx block) owns one
  // shared "which category is open" value across every CategorySubmenu in its list, so opening
  // one always closes any other that was open.
  isOpen: boolean
  onOpen: () => void
  onClose: () => void
  children: ReactNode
  /** Shown before `name` (the header menu's Filter item) */
  icon?: ReactNode
  /** Names the flyout as a group (the header menu's filter controls) */
  groupLabel?: string
  /** Extra style on the flyout */
  panelStyle?: CSSProperties
}

const triggerStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  padding: '7px 14px',
  cursor: 'pointer',
  fontSize: 13,
  color: 'var(--color-text-primary)',
  border: 'none',
  background: 'none',
  fontFamily: 'inherit',
  textAlign: 'left',
  margin: 0,
  width: '100%',
  boxSizing: 'border-box',
}
const arrowStyle: CSSProperties = {
  flexShrink: 0,
  fontSize: 10,
  color: 'var(--color-text-tertiary)',
}
const submenuStyle: CSSProperties = {
  position: 'fixed',
  zIndex: 101,
  background: 'var(--color-background-primary)',
  border: '0.5px solid var(--color-border-secondary)',
  borderRadius: 8,
  boxShadow: '0 4px 16px rgba(0,0,0,0.10)',
  minWidth: 160,
  maxHeight: 320,
  overflowY: 'auto',
  padding: '4px 0',
}

// A category row in the Sort/Group dropdowns' addable-column lists (see docs/columns.md's "Column
// categories"): collapses every column sharing `ColumnDefBase.category` into one row that opens a
// flyout submenu listing them, instead of a flat run of individual rows — worthwhile once a
// category has enough columns that this saves real scanning. Mirrors
// `packages/solid/src/components/CategorySubmenu.tsx` — same design, ported to React's own
// ref/layout-effect idioms instead of Solid's signals.
//
// Positioned with `position: fixed` at viewport coordinates computed from the trigger's own rect
// (`computeSubmenuPosition`, core), but rendered as a plain sibling of the trigger — NOT portaled
// to `document.body`, and NOT `position: absolute` either. Solid's own first version used
// `position: absolute` and hit a real bug: `.dt-dd`'s `overflow-y: auto` (see `Dropdown.tsx`'s
// panel style) means an absolutely positioned descendant that overflows a scrollable ancestor
// horizontally still grows that ancestor's own scrollable region even though it's out of normal
// flow — clipping the flyout and adding a spurious horizontal scrollbar to the whole panel. A
// `createPortal` to `document.body` was tried next and does dodge that, but comes with a real
// cost: a portaled node is no longer a DOM descendant of whatever ancestor a consumer scopes theme
// CSS custom properties to (if that ancestor is narrower than `<body>`), so the submenu silently
// falls back to the library's baked-in default colors instead of inheriting the consumer's theme
// (GitHub issue #23). `position: fixed` alone turns out to solve the original overflow problem on
// its own, with no portal needed: a fixed element's containing block is the *viewport*, not any
// scrolling ancestor, unless that ancestor sets `transform`/`filter`/`perspective`/
// `will-change: transform` (none of `.dt-dd`'s chrome does) — so a fixed submenu never contributes
// to `.dt-dd`'s scrollable area in the first place, portal or not.
//
// Because the submenu is a real DOM descendant of the panel again, its `data-dd-row`-marked rows
// *are* reachable by `Dropdown.tsx`'s own generic panel-wide roving nav — which is exactly why
// that nav explicitly excludes anything inside `[data-category-submenu]` (see its own comment):
// `handleSubmenuKeyDown` below is still what should drive Up/Down/Home/End while the submenu is
// open, not the panel's. It calls `stopPropagation()` so `Dropdown.tsx`'s own panel-level handler
// never double-handles the same keydown.
export function CategorySubmenu(props: CategorySubmenuProps) {
  const [left, setLeft] = useState(0)
  const [top, setTop] = useState(0)
  const triggerRef = useRef<HTMLButtonElement>(null)
  const submenuRef = useRef<HTMLDivElement>(null)
  const openTimerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined)
  const closeTimerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined)

  function cancelOpen(): void {
    if (openTimerRef.current) {
      clearTimeout(openTimerRef.current)
      openTimerRef.current = undefined
    }
  }
  function cancelClose(): void {
    if (closeTimerRef.current) {
      clearTimeout(closeTimerRef.current)
      closeTimerRef.current = undefined
    }
  }

  function focusFirstRow(): void {
    queueMicrotask(() => {
      const submenu = submenuRef.current
      if (!submenu) return
      // A flyout without rows (the header menu's filter pane) starts on its first text field
      ;(
        ddNavFocusables(submenu)[0] ??
        submenu.querySelector<HTMLElement>('input[type=text]') ??
        submenu.querySelector<HTMLElement>('input, button')
      )?.focus()
    })
  }
  function openNow(focusFirst: boolean): void {
    cancelOpen()
    cancelClose()
    if (!props.isOpen) {
      if (triggerRef.current) {
        // Initial guess (right of the trigger, top-aligned) — corrected by the layout effect
        // below once the submenu's real size is known. Avoids a 0,0-positioned flash before that
        // measurement lands.
        const rect = triggerRef.current.getBoundingClientRect()
        setLeft(rect.right)
        setTop(rect.top)
      }
      props.onOpen()
    }
    if (focusFirst) focusFirstRow()
  }
  function closeNow(focusTrigger: boolean): void {
    cancelOpen()
    cancelClose()
    if (props.isOpen) props.onClose()
    if (focusTrigger) triggerRef.current?.focus()
  }
  function scheduleOpen(): void {
    cancelClose()
    if (props.isOpen || openTimerRef.current) return
    openTimerRef.current = setTimeout(() => {
      openTimerRef.current = undefined
      openNow(false)
    }, OPEN_DELAY)
  }
  function scheduleClose(): void {
    cancelOpen()
    if (closeTimerRef.current) return
    closeTimerRef.current = setTimeout(() => {
      closeTimerRef.current = undefined
      closeNow(false)
    }, CLOSE_DELAY)
  }

  // Corrects the initial guess above once the submenu's real size is known — runs synchronously
  // after the DOM update (before paint), same reasoning as Dropdown.tsx's own viewport-clamp
  // layout effect.
  useLayoutEffect(() => {
    if (!props.isOpen) return
    const trigger = triggerRef.current
    const submenu = submenuRef.current
    if (!trigger || !submenu) return
    const triggerRect = trigger.getBoundingClientRect()
    const rect = submenu.getBoundingClientRect()
    const pos = computeSubmenuPosition(
      triggerRect,
      { width: rect.width, height: rect.height },
      viewportWidth(),
      window.innerHeight,
    )
    setLeft(pos.left)
    setTop(pos.top)
  }, [props.isOpen])

  function handleSubmenuKeyDown(e: KeyboardEvent<HTMLDivElement>): void {
    // ← in a text field moves its caret instead
    const inText = e.target instanceof HTMLInputElement && e.target.type !== 'checkbox'
    if (e.key === 'Escape' || (e.key === 'ArrowLeft' && !inText)) {
      e.preventDefault()
      e.stopPropagation()
      closeNow(true)
      return
    }
    if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp' && e.key !== 'Home' && e.key !== 'End') return
    const submenu = submenuRef.current
    if (!submenu) return
    const focusables = ddNavFocusables(submenu)
    const active = document.activeElement as HTMLElement | null
    const idx = active ? focusables.indexOf(active) : -1
    if (idx === -1) return
    e.stopPropagation()
    if (e.key === 'Home' || e.key === 'End') {
      e.preventDefault()
      ;(e.key === 'Home' ? focusables[0] : focusables[focusables.length - 1])?.focus()
      return
    }
    const nextIdx = e.key === 'ArrowDown' ? idx + 1 : idx - 1
    if (nextIdx < 0 || nextIdx >= focusables.length) return
    e.preventDefault()
    focusables[nextIdx]?.focus()
  }

  return (
    <div style={{ position: 'relative' }}>
      <button
        type="button"
        data-dd-row
        data-category-header={props.name}
        ref={triggerRef}
        aria-expanded={props.isOpen}
        onMouseEnter={scheduleOpen}
        onMouseLeave={scheduleClose}
        onClick={() => (props.isOpen ? closeNow(false) : openNow(true))}
        onKeyDown={(e) => {
          if (e.key === 'ArrowRight' && !props.isOpen) {
            e.preventDefault()
            openNow(true)
          }
        }}
        style={triggerStyle}
      >
        {props.icon}
        <span style={{ flex: 1 }}>{props.name}</span>
        <span style={arrowStyle}>▸</span>
      </button>
      {props.isOpen && (
        <div
          ref={submenuRef}
          data-category-submenu
          role={props.groupLabel ? 'group' : undefined}
          aria-label={props.groupLabel}
          onMouseEnter={cancelClose}
          onMouseLeave={scheduleClose}
          onKeyDown={handleSubmenuKeyDown}
          style={{ ...submenuStyle, ...props.panelStyle, left, top }}
        >
          {props.children}
        </div>
      )}
    </div>
  )
}
