// packages/solid/src/components/Dropdown.tsx
import { type JSX, Show, createSignal, onCleanup, onMount } from 'solid-js'
import { computeDropdownClampOffset, ddNavFocusables } from '@vates/data-table-core/internal'

interface DropdownProps {
  isOpen: boolean
  onToggle: () => void
  onClose: () => void
  trigger: JSX.Element
  /** Rendered as a sibling of `trigger`, inside the same outside-click boundary — see the
   * toolbar's per-dropdown × clear buttons (docs/toolbar.md's "Toolbar clear buttons"). */
  extraTrigger?: JSX.Element
  children: JSX.Element
  /**
   * Escape clears a non-empty search term first (focus stays put), only closing the dropdown on
   * a second press or when there was nothing to clear — each dropdown wires its own search-clear
   * action here (it may own more than one search box, e.g. the Filter dropdown's column search
   * and its per-column value search; the callback itself decides which one Escape's own moment
   * actually applies to, checking `document.activeElement`). Returns whether it actually cleared
   * something. Omitted for a panel with no search box at all.
   */
  onEscapeClearable?: () => boolean
}

// `data-dd-search` marks a dropdown's own column-search `<input>` (Columns/Sort/Group's addable
// list, Filter's left pane); `data-dd-row` marks every other row this nav should reach (a column
// checkbox row, a Sort/Group active or addable entry, a Filter column-selector button). Handled by
// core's `ddNavFocusables` (`@vates/data-table-core/dropdownDomUtils`, using its default
// `DD_NAV_SELECTOR`), shared with react/components/Dropdown.tsx's identical usage — deliberately
// generic, since Dropdown has no idea which concrete dropdown it's rendering, only that its
// children may carry these two markers. The Filter dropdown's own right-pane value search/checklist
// get separate `data-dd-value-search`/`data-dd-value-row` markers instead (see FilterDropdown.tsx)
// — a distinct focusable-set with its own nav, not covered by this one.

// Generic dropdown shell shared by Columns/Sort/Group/Filter — mirrors react/components/Dropdown.tsx
// and vue/components/Dropdown.vue's role. Handles: open/close, outside-click-to-close,
// Escape-clears-search-then-closes, focus-follows-open, roving Up/Down/Home/End nav across the
// panel's own search box + rows, and viewport clamping (translateX so a wide panel opened near
// the right edge doesn't render off-screen — see docs/toolbar.md's "Dropdown viewport clamping").
export function Dropdown(props: DropdownProps) {
  let wrapRef: HTMLDivElement | undefined
  let panelRef: HTMLDivElement | undefined
  const [flipUp, setFlipUp] = createSignal(false)
  const [translateX, setTranslateX] = createSignal(0)

  function handleDocClick(e: MouseEvent): void {
    // Every Columns/Sort/Group/Filter dropdown mounts its own Dropdown instance simultaneously,
    // each with its own document-level capture listener. Without this `props.isOpen` guard, a
    // click anywhere inside the *currently open* dropdown's own panel would still be treated as
    // "outside" by every *other*, currently-closed dropdown's listener — and since all four share
    // one `openDropdown` signal, any of their `onClose()` calls closes whichever one actually is
    // open, immediately after the click reaches its real target. (Found via the full
    // createDataTable integration tests: it never surfaced in a single-component test, since
    // there's no sibling dropdown there to falsely fire.)
    if (!props.isOpen) return
    if (wrapRef && !wrapRef.contains(e.target as Node)) props.onClose()
  }

  // Roving Up/Down/Home/End nav across the panel's own search box + rows (see DD_NAV_SELECTOR
  // above), plus Escape. A distinct concern from any Alt+↑/↓ reorder or Enter/Space toggle a row
  // itself implements — those don't stopPropagation, so this still runs after them via bubbling,
  // but its own `e.altKey` guard keeps it from ever acting on their modifier combo. Scoped to
  // elements this panel actually recognizes (`focusables.indexOf(active) !== -1`) so it never
  // interferes with unrelated controls elsewhere in the panel (e.g. the Filter dropdown's
  // right-hand detail pane, which implements its own nav — see FilterDropdown.tsx — including
  // native Left/Right/Up/Down/Home/End on its own range inputs/slider that must keep working
  // unmolested).
  function handleKeyDown(e: KeyboardEvent): void {
    if (e.key === 'Escape') {
      e.stopPropagation()
      if (props.onEscapeClearable?.()) return
      props.onClose()
      // The trigger is always the first <button> in DOM order (trigger renders before
      // extraTrigger, which renders before the panel) — same technique react's own Dropdown uses.
      wrapRef?.querySelector<HTMLElement>('button')?.focus()
      return
    }
    if (e.altKey) return
    if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp' && e.key !== 'Home' && e.key !== 'End') return
    if (!panelRef) return
    // A CategorySubmenu (see that file) renders as a real descendant of this panel and implements
    // its own independent Up/Down/Home/End nav, scoped to its own rows and stopping propagation —
    // excluding its rows here keeps this panel-wide nav exactly as if the submenu weren't open,
    // rather than letting it wander into a floating submenu whose rows aren't visually part of
    // this list.
    const focusables = ddNavFocusables(panelRef).filter((el) => !el.closest('.dt-dd-submenu'))
    const rowFocusables = focusables.filter((el) => !el.matches('input[data-dd-search]'))
    const active = document.activeElement as HTMLElement | null
    if (!active || focusables.indexOf(active) === -1) return
    if (e.key === 'Home' || e.key === 'End') {
      if (rowFocusables.length === 0) return
      e.preventDefault()
      ;(e.key === 'Home' ? rowFocusables[0] : rowFocusables[rowFocusables.length - 1]).focus()
      return
    }
    const idx = focusables.indexOf(active)
    const nextIdx = e.key === 'ArrowDown' ? idx + 1 : idx - 1
    if (nextIdx < 0 || nextIdx >= focusables.length) return
    e.preventDefault()
    focusables[nextIdx].focus()
  }

  onMount(() => {
    document.addEventListener('click', handleDocClick, true)
    onCleanup(() => document.removeEventListener('click', handleDocClick, true))
  })

  function clampToViewport(el: HTMLDivElement): void {
    const rect = el.getBoundingClientRect()
    const { dx, flipUp } = computeDropdownClampOffset(rect, window.innerWidth, window.innerHeight)
    setTranslateX(dx)
    setFlipUp(flipUp)
  }

  return (
    <div class="dt-dd-wrap" ref={wrapRef} onKeyDown={handleKeyDown}>
      <span style={{ display: 'inline-flex' }}>
        {props.trigger}
        {props.extraTrigger}
      </span>
      <Show when={props.isOpen}>
        <div
          class={`dt-dd${flipUp() ? ' dt-dd--up' : ''}`}
          ref={(el) => {
            panelRef = el
            // A ref callback fires at this element's own insertion time — before `props.children`
            // (passed down from Columns/Sort/Group/Filter, several component boundaries away) has
            // actually been resolved and appended underneath it. Querying for a search box/row
            // synchronously here found nothing every time (confirmed by a failing test) — same
            // underlying reason the viewport-clamp measurement below already needs to wait a
            // microtask, just for DOM presence instead of layout.
            queueMicrotask(() => {
              if (!panelRef) return
              // Opening a dropdown should hand it focus immediately — its own search box if it
              // has one (preferred regardless of where it sits in the DOM, e.g. Sort/Group's
              // search box renders *after* the active-entries section but is still the preferred
              // landing spot), else the first row (e.g. Sort with every column already sorted has
              // no addable section and therefore no search box).
              const search = panelRef.querySelector<HTMLElement>('input[data-dd-search]')
              if (search) search.focus()
              else ddNavFocusables(panelRef)[0]?.focus()
              // Measure after the panel's real content is laid out — same microtask, since both
              // now depend on the same "children actually exist" precondition.
              clampToViewport(panelRef)
            })
          }}
          style={{ transform: translateX() ? `translateX(${translateX()}px)` : undefined }}
        >
          {props.children}
        </div>
      </Show>
    </div>
  )
}

// packages/react/src/components/Dropdown.tsx
import {
  useRef,
  useEffect,
  useLayoutEffect,
  type DragEvent,
  type KeyboardEvent,
  type ReactNode,
} from 'react'
import {
  computeDropdownClampOffset,
  ddNavFocusables,
  viewportWidth,
} from '@vates/data-table-core/internal'

export interface DropdownProps {
  trigger: ReactNode
  children: ReactNode
  open: boolean
  setOpen: (open: boolean) => void
  // Bound to the panel itself (not per-row) so a drag-and-drop reorder list inside can resolve
  // a drop that lands past its last row / in unrelated dead space — see the Sort/Group/Columns
  // dropdown drag handlers in DataTableView.tsx.
  onDragOver?: (e: DragEvent<HTMLDivElement>) => void
  onDrop?: (e: DragEvent<HTMLDivElement>) => void
  // Rendered as a sibling of the trigger — inside the same outside-click boundary as the trigger
  // and panel (so clicking it doesn't spuriously close the dropdown via the "click outside"
  // handler below), but outside the trigger's own onClick toggle (so it never opens/closes the
  // dropdown itself). Used for the Sort/Group/Filter toolbar's adjoining × clear button (see
  // DataTableView.tsx), visually merged into one pill with the trigger via shared CSS.
  extraTrigger?: ReactNode
}

// The panel's roving Up/Down/Home/End nav (see the keydown handler below) and its focus-on-open
// behavior (see the layout effect below) both need the same "ordered list of this panel's own
// focusable row/search elements" — `ddNavFocusables` (core's `dropdownDomUtils`, using its default
// `DD_NAV_SELECTOR`) provides this, shared with Solid's identical usage. `data-dd-search` marks a
// dropdown's own column-search input (Columns/Sort/Group's addable list/Filter's left pane, see
// DataTableView.tsx); `data-dd-row` marks every other row this nav should reach (a column
// checkbox row, a Sort/Group active or addable entry, a Filter column-selector button). This is
// deliberately generic — Dropdown has no idea which concrete dropdown it's rendering, only that
// its children may carry these two markers.

export function Dropdown({
  trigger,
  children,
  open,
  setOpen,
  onDragOver,
  onDrop,
  extraTrigger,
}: DropdownProps) {
  const ref = useRef<HTMLDivElement>(null)
  const panelRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [setOpen])

  // The panel unmounts entirely when closed, so each open is a fresh DOM node at its natural
  // (unclamped) position — this mutates that node's style directly rather than going through
  // React state (which would need a setState-in-effect, flagged as a cascading-render risk by
  // this project's eslint-plugin-react-hooks config). A translateX offset is used for the
  // horizontal case instead of flipping left:0 -> right:0, since the overflow is relative to
  // the viewport, not to the trigger (see vanilla's Dropdown clamp for the reasoning).
  useLayoutEffect(() => {
    if (!open) return
    const panel = panelRef.current
    if (!panel) return
    const rect = panel.getBoundingClientRect()
    const { dx, flipUp } = computeDropdownClampOffset(rect, viewportWidth(), window.innerHeight)
    if (dx !== 0) panel.style.transform = `translateX(${dx}px)`
    if (flipUp) {
      panel.style.top = 'auto'
      panel.style.marginTop = '0'
      panel.style.bottom = '100%'
      panel.style.marginBottom = '4px'
    }
    // Opening a dropdown should hand it focus immediately — its own search box if it has one
    // (preferred regardless of where it sits in the DOM, e.g. Sort/Group's search box renders
    // *after* the active-entries section but is still the preferred landing spot, matching
    // vanilla's focusFirstInDropdown), else the first row (e.g. Sort with every column already
    // sorted has no addable section and therefore no search box).
    const search = panel.querySelector<HTMLElement>('input[data-dd-search]')
    if (search) search.focus()
    else ddNavFocusables(panel)[0]?.focus()
  }, [open])

  // Roving Up/Down/Home/End/Escape navigation across this panel's own search box + rows — see
  // DD_NAV_SELECTOR above. A distinct concern from any Alt+↑/↓ reorder or Enter/Space toggle a
  // row itself implements (see the Sort/Group active rows in DataTableView.tsx): those don't
  // stopPropagation, so this still runs after them via bubbling, but its own `!e.altKey` guard
  // keeps it from ever acting on their modifier combo. Scoped to elements this panel actually
  // recognizes (`focusables.indexOf(active) !== -1`) so it never interferes with unrelated
  // controls elsewhere in the panel (e.g. the Filter dropdown's right-hand detail pane, which
  // implements its own nav — see handleFilterPanelKeyDown in DataTableView.tsx — including native
  // Left/Right/Up/Down/Home/End on its own range inputs/slider that must keep working unmolested).
  const handlePanelKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    if (e.altKey) return
    if (e.key === 'Escape') {
      e.preventDefault()
      setOpen(false)
      ref.current?.querySelector<HTMLElement>('button')?.focus()
      return
    }
    if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp' && e.key !== 'Home' && e.key !== 'End') return
    const panel = panelRef.current
    if (!panel) return
    // A CategorySubmenu (see that file) renders as a real descendant of this panel and implements
    // its own independent Up/Down/Home/End nav, scoped to its own rows and stopping propagation —
    // excluding its rows here keeps this panel-wide nav exactly as if the submenu weren't open,
    // rather than letting it wander into a floating submenu whose rows aren't visually part of
    // this list.
    const focusables = ddNavFocusables(panel).filter((el) => !el.closest('[data-category-submenu]'))
    const rowFocusables = focusables.filter((el) => !el.matches('input[data-dd-search]'))
    const active = document.activeElement as HTMLElement | null
    if (!active || focusables.indexOf(active) === -1) return
    if (e.key === 'Home' || e.key === 'End') {
      if (rowFocusables.length === 0) return
      e.preventDefault()
      ;(e.key === 'Home' ? rowFocusables[0] : rowFocusables[rowFocusables.length - 1]).focus()
      return
    }
    const idx = focusables.indexOf(active)
    const nextIdx = e.key === 'ArrowDown' ? idx + 1 : idx - 1
    if (nextIdx < 0 || nextIdx >= focusables.length) return
    e.preventDefault()
    focusables[nextIdx].focus()
  }

  return (
    <div ref={ref} style={{ position: 'relative', display: 'inline-flex' }}>
      <div onClick={() => setOpen(!open)}>{trigger}</div>
      {extraTrigger}
      {open && (
        <div
          ref={panelRef}
          onDragOver={onDragOver}
          onDrop={onDrop}
          onKeyDown={handlePanelKeyDown}
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            zIndex: 100,
            marginTop: 4,
            background: 'var(--color-background-primary)',
            border: '0.5px solid var(--color-border-secondary)',
            borderRadius: 8,
            boxShadow: '0 4px 16px rgba(0,0,0,0.10)',
            minWidth: 220,
            maxHeight: 420,
            overflowY: 'auto',
            padding: '4px 0',
          }}
        >
          {children}
        </div>
      )}
    </div>
  )
}
