// packages/vue/src/components/HeaderMenu.vue
<script setup lang="ts" generic="TRow extends object">
import { computed, nextTick, onUnmounted, ref } from 'vue'
import {
  FILTER_NARROW_QUERY,
  HEADER_MENU_ITEMS,
  columnHasActiveFilter,
  ddNavFocusables,
  getHeaderMenuItems,
  keepHeaderMenuFocus,
  moveMenuIndex,
  onMenuDismiss,
  placeMenu,
  watchMedia,
  type HeaderMenuItem,
} from '@vates/data-table-core/internal'
import type { ColumnDef } from '../types'
import type { TableState } from '../useTableState'
import CategorySubmenu from './CategorySubmenu.vue'
import FilterPane from './FilterPane.vue'

// A header's ▾ menu. `position: fixed` (like CategorySubmenu) so the table's scrolling wrapper
// doesn't clip it; it closes on any scroll rather than tracking its header.
const props = defineProps<{
  table: TableState<TRow>
  col: ColumnDef<TRow>
  data: TRow[]
  columns: ColumnDef<TRow>[]
}>()
const emit = defineEmits<{ openChange: [open: boolean] }>()
// `value`: the filter flyout's value label, forwarded to FilterPane
// `label`: the value through the column's `format`, the default content
defineSlots<{ value?: (props: { value: string; label: string }) => unknown }>()

const ROW_SELECTOR = 'button.dt__dd-item--clickable'

const open = ref(false)
const filterOpen = ref(false)
const pos = ref({ left: 0, top: 0 })
const triggerRef = ref<HTMLButtonElement | null>(null)
const menuRef = ref<HTMLDivElement | null>(null)
let stopDismiss: (() => void) | undefined
// No room for a flyout beside the menu: Filter swaps the panel's items for its pane instead
const narrow = ref(false)
const stopWatch = watchMedia(FILTER_NARROW_QUERY, (m) => (narrow.value = m))
const drilled = computed(() => narrow.value && filterOpen.value)

const L = props.table.labels
const items = computed(() =>
  getHeaderMenuItems(
    props.col,
    props.table.group.by.value,
    props.table.columns.active.value.length,
    isFiltered.value,
  ),
)
const isFiltered = computed(() =>
  columnHasActiveFilter(
    props.col.key,
    props.table.filter.include.value,
    props.table.filter.exclude.value,
    props.table.filter.ranges.value,
  ),
)

onUnmounted(() => {
  stopWatch()
  stopDismiss?.()
  if (open.value) emit('openChange', false)
})

async function openMenu(): Promise<void> {
  open.value = true
  emit('openChange', true)
  stopDismiss = onMenuDismiss(
    () => [menuRef.value, triggerRef.value],
    () => close(false),
  )
  await nextTick()
  if (!menuRef.value || !triggerRef.value) return
  pos.value = placeMenu(triggerRef.value, menuRef.value)
  ddNavFocusables(menuRef.value, ROW_SELECTOR)[0]?.focus()
}
function close(focusTrigger: boolean): void {
  open.value = false
  filterOpen.value = false
  emit('openChange', false)
  stopDismiss?.()
  if (focusTrigger) triggerRef.value?.focus()
}

// Focuses the back row rather than the search box, so the on-screen keyboard waits for a tap
async function drill(into: boolean): Promise<void> {
  filterOpen.value = into
  await nextTick()
  if (!menuRef.value || !triggerRef.value) return
  pos.value = placeMenu(triggerRef.value, menuRef.value)
  menuRef.value
    .querySelector<HTMLElement>(into ? '[data-menu-back]' : '[data-menu-filter]')
    ?.focus()
}
function onPaneKeydown(e: KeyboardEvent): void {
  // ← in a text field moves its caret instead
  const inText = e.target instanceof HTMLInputElement && e.target.type !== 'checkbox'
  if (e.key !== 'Escape' && (e.key !== 'ArrowLeft' || inText)) return
  e.preventDefault()
  e.stopPropagation()
  void drill(false)
}

// Grouping or hiding can remove this header: focus the ▾ now at its position instead
function act(item: Exclude<HeaderMenuItem, 'filter'>): void {
  const restoreFocus = triggerRef.value && keepHeaderMenuFocus(triggerRef.value)
  close(true)
  if (item === 'clear')
    for (const kind of ['include', 'exclude', 'range'] as const)
      props.table.filter.clearColumn(props.col.key, kind)
  else if (item === 'group' || item === 'ungroup') props.table.group.toggle(props.col.key)
  else props.table.columns.toggleVisibility(props.col.key)
  if (restoreFocus) void nextTick(restoreFocus)
}

// Focus leaving the panel closes it; a click inside may blur to nothing (null)
function onMenuFocusout(e: FocusEvent): void {
  const to = e.relatedTarget as Node | null
  if (to && !menuRef.value?.contains(to) && to !== triggerRef.value) close(false)
}

function onMenuKeydown(e: KeyboardEvent): void {
  // Keys inside the filter flyout are the flyout's
  if ((e.target as Element).closest('.dt__th-filter-flyout')) return
  if (e.key === 'Escape') {
    e.preventDefault()
    close(true)
    return
  }
  if (!menuRef.value) return
  const rows = ddNavFocusables(menuRef.value, ROW_SELECTOR)
  const next = moveMenuIndex(
    e.key,
    rows.indexOf(document.activeElement as HTMLElement),
    rows.length,
  )
  if (next === null) return
  e.preventDefault()
  rows[next]?.focus()
}
</script>

<template>
  <template v-if="items.length > 0">
    <button
      ref="triggerRef"
      type="button"
      class="dt__th-menu"
      :class="{ 'dt__th-menu--filtered': isFiltered }"
      data-col-menu
      :aria-label="L.columnMenu(col.label, isFiltered)"
      aria-haspopup="dialog"
      :aria-expanded="open"
      draggable="false"
      @click.stop="open ? close(false) : openMenu()"
    >
      <!-- A funnel, not just a color, tells a filtered column apart -->
      <svg
        v-if="isFiltered"
        class="dt__th-menu-icon"
        viewBox="0 0 16 16"
        fill="none"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linejoin="round"
        aria-hidden="true"
      >
        <path :d="HEADER_MENU_ITEMS.filter.icon" />
      </svg>
      <template v-else>▾</template>
    </button>
    <div
      v-if="open"
      ref="menuRef"
      class="dt__dd-submenu dt__th-menu-panel"
      :class="{ 'dt__th-menu-panel--drilled': drilled }"
      role="dialog"
      :aria-label="L.columnMenu(col.label, false)"
      :style="{ position: 'fixed', left: `${pos.left}px`, top: `${pos.top}px` }"
      @click.stop
      @keydown="onMenuKeydown"
      @focusout="onMenuFocusout"
    >
      <div
        v-if="drilled"
        class="dt__th-filter-flyout"
        role="group"
        :aria-label="L.filter"
        @keydown="onPaneKeydown"
      >
        <button
          type="button"
          class="dt__dd-item dt__dd-item--clickable dt__th-menu-back"
          data-menu-back
          @click="drill(false)"
        >
          ‹ {{ col.label }}
        </button>
        <FilterPane :table="table" :col="col" :data="data" :columns="columns">
          <template #value="{ value, label }"
            ><slot name="value" :value="value" :label="label"
          /></template>
        </FilterPane>
      </div>
      <template v-else>
        <template v-for="item in items" :key="item">
          <button
            v-if="item === 'filter' && narrow"
            type="button"
            class="dt__dd-item dt__dd-item--clickable"
            data-menu-filter
            @click="drill(true)"
            @keydown.right="drill(true)"
          >
            <svg
              class="dt__th-menu-icon"
              viewBox="0 0 16 16"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path :d="HEADER_MENU_ITEMS[item].icon" />
            </svg>
            <span class="dt__th-menu-label">{{ L[HEADER_MENU_ITEMS[item].label] }}</span>
            <span class="dt__th-menu-arrow">▸</span>
          </button>
          <CategorySubmenu
            v-else-if="item === 'filter'"
            :name="L[HEADER_MENU_ITEMS[item].label]"
            :group-label="L[HEADER_MENU_ITEMS[item].label]"
            submenu-class="dt__th-filter-flyout"
            :is-open="filterOpen"
            @open="filterOpen = true"
            @close="filterOpen = false"
          >
            <template #icon>
              <svg
                class="dt__th-menu-icon"
                viewBox="0 0 16 16"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linejoin="round"
                aria-hidden="true"
              >
                <path :d="HEADER_MENU_ITEMS[item].icon" />
              </svg>
            </template>
            <FilterPane :table="table" :col="col" :data="data" :columns="columns">
              <template #value="{ value, label }"
                ><slot name="value" :value="value" :label="label"
              /></template>
            </FilterPane>
          </CategorySubmenu>
          <button
            v-else
            type="button"
            class="dt__dd-item dt__dd-item--clickable"
            @click="act(item)"
          >
            <svg
              class="dt__th-menu-icon"
              viewBox="0 0 16 16"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path :d="HEADER_MENU_ITEMS[item].icon" />
            </svg>
            {{ L[HEADER_MENU_ITEMS[item].label] }}
          </button>
        </template>
      </template>
    </div>
  </template>
</template>

<style scoped>
.dt__th-menu {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  width: 24px;
  height: 24px;
  margin: -4px 0 -4px auto;
  padding: 0;
  border: none;
  border-radius: 4px;
  background: none;
  color: var(--color-text-secondary);
  font: inherit;
  cursor: pointer;
}
.dt__th-menu:hover,
.dt__th-menu[aria-expanded='true'] {
  background: var(--color-background-secondary);
}
.dt__th-menu--filtered {
  color: var(--color-text-info);
  font-weight: 700;
}
.dt__dd-submenu {
  z-index: 101;
  background: var(--color-background-primary);
  border: 0.5px solid var(--color-border-secondary);
  border-radius: 8px;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
  min-width: 160px;
  max-height: 320px;
  overflow-y: auto;
  padding: 4px 0;
  font-weight: 400;
}
.dt__dd-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 7px 14px;
  font-size: 13px;
  color: var(--color-text-primary);
  border: none;
  background: none;
  font-family: inherit;
  text-align: left;
  margin: 0;
  width: 100%;
  box-sizing: border-box;
}
.dt__dd-item--clickable {
  cursor: pointer;
}
.dt__dd-item--clickable:hover,
.dt__dd-item--clickable:focus {
  background: var(--color-background-secondary);
}
/* The icon in the Filter item sits in CategorySubmenu's trigger, the flyout in its template */
:deep(.dt__th-menu-icon),
.dt__th-menu-icon {
  width: 14px;
  height: 14px;
  flex-shrink: 0;
}
.dt__th-menu-panel {
  /* 100vw counts a classic scrollbar too, hence more than twice the 8 px viewport margin */
  max-width: calc(100vw - 40px);
}
/* Holds the filter pane itself, which scrolls its own list */
.dt__th-menu-panel--drilled {
  max-height: none;
  overflow: hidden;
  padding: 0;
}
.dt__th-menu-back {
  flex-shrink: 0;
  font-weight: 500;
  border-bottom: 0.5px solid var(--color-border-tertiary);
}
.dt__th-menu-label {
  flex: 1;
}
.dt__th-menu-arrow {
  flex-shrink: 0;
  font-size: 10px;
  color: var(--color-text-tertiary);
}
.dt__th-filter-flyout,
:deep(.dt__dd-submenu.dt__th-filter-flyout) {
  display: flex;
  flex-direction: column;
  max-height: 380px;
  overflow: hidden;
  padding: 0;
}
</style>

// packages/react/src/components/HeaderMenu.tsx
import {
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent,
  type ReactNode,
} from 'react'
import {
  FILTER_NARROW_QUERY,
  HEADER_MENU_ITEMS,
  ddNavFocusables,
  keepHeaderMenuFocus,
  moveMenuIndex,
  onMenuDismiss,
  placeMenu,
  watchMedia,
  type HeaderMenuItem,
} from '@vates/data-table-core/internal'
import type { DataTableLabels } from '@vates/data-table-core'
import { CategorySubmenu } from './CategorySubmenu'

interface HeaderMenuProps {
  /** Accessible name of the ▾ button */
  label: string
  /** Accessible name of the panel */
  menuLabel: string
  /** The column's label, naming the narrow screen's back row */
  column: string
  labels: DataTableLabels
  /** From `getHeaderMenuItems`; empty renders nothing */
  items: HeaderMenuItem[]
  filtered: boolean
  /** The column's filter pane, shown in the Filter flyout */
  filterPane: ReactNode
  onClearFilter: () => void
  onGroup: () => void
  onHide: () => void
}

const triggerStyle: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  flexShrink: 0,
  width: 24,
  height: 24,
  margin: '-4px 0 -4px auto',
  padding: 0,
  border: 'none',
  borderRadius: 4,
  background: 'none',
  color: 'var(--color-text-secondary)',
  fontFamily: 'inherit',
  fontSize: 'inherit',
  cursor: 'pointer',
}
const panelStyle: CSSProperties = {
  position: 'fixed',
  zIndex: 101,
  background: 'var(--color-background-primary)',
  border: '0.5px solid var(--color-border-secondary)',
  borderRadius: 8,
  boxShadow: '0 4px 16px rgba(0,0,0,0.10)',
  minWidth: 160,
  // 100vw counts a classic scrollbar too, hence more than twice the 8 px viewport margin
  maxWidth: 'calc(100vw - 40px)',
  maxHeight: 320,
  overflowY: 'auto',
  padding: '4px 0',
  fontWeight: 400,
}
// Holds the filter pane itself, which scrolls its own list
const drilledPanelStyle: CSSProperties = {
  ...panelStyle,
  maxHeight: 'none',
  overflow: 'hidden',
  padding: 0,
}
const backStyle: CSSProperties = {
  flexShrink: 0,
  fontWeight: 500,
  borderBottom: '0.5px solid var(--color-border-tertiary)',
}
const arrowStyle: CSSProperties = {
  flexShrink: 0,
  fontSize: 10,
  color: 'var(--color-text-tertiary)',
}
const itemStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  padding: '7px 14px',
  cursor: 'pointer',
  fontSize: 13,
  color: 'var(--color-text-primary)',
  border: 'none',
  background: 'none',
  fontFamily: 'inherit',
  textAlign: 'left',
  margin: 0,
  width: '100%',
  boxSizing: 'border-box',
}
const flyoutStyle: CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  maxHeight: 380,
  overflow: 'hidden',
  padding: 0,
}
const hoverBg = 'var(--color-background-secondary)'

function Icon({ item }: { item: HeaderMenuItem }) {
  return (
    <svg
      viewBox="0 0 16 16"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinejoin="round"
      aria-hidden="true"
      style={{ width: 14, height: 14, flexShrink: 0 }}
    >
      <path d={HEADER_MENU_ITEMS[item].icon} />
    </svg>
  )
}

// A header's ▾ menu. `position: fixed` (like CategorySubmenu) so the table's scrolling wrapper
// doesn't clip it; it closes on any scroll rather than tracking its header. Mirrors Solid's
// HeaderMenu.tsx; the shared logic lives in core's headerMenu.ts.
export function HeaderMenu({
  label,
  menuLabel,
  column,
  labels: L,
  items,
  filtered,
  filterPane,
  onClearFilter,
  onGroup,
  onHide,
}: HeaderMenuProps) {
  const [open, setOpen] = useState(false)
  const [filterOpen, setFilterOpen] = useState(false)
  const [pos, setPos] = useState({ left: 0, top: 0 })
  // Hovered/focused item (inline styles have no :hover/:focus); -1 is the trigger
  const [lit, setLit] = useState<number | null>(null)
  const triggerRef = useRef<HTMLButtonElement>(null)
  const menuRef = useRef<HTMLDivElement>(null)
  // No room for a flyout beside the menu: Filter swaps the panel's items for its pane instead
  const [narrow, setNarrow] = useState(false)
  useEffect(() => watchMedia(FILTER_NARROW_QUERY, setNarrow), [])
  const drilled = narrow && filterOpen
  const drillFocus = useRef<string | null>(null)

  useLayoutEffect(() => {
    const menu = menuRef.current
    const trigger = triggerRef.current
    if (!open || !menu || !trigger) return
    setPos(placeMenu(trigger, menu))
    ddNavFocusables(menu)[0]?.focus()
  }, [open])

  // Focuses the back row rather than the search box, so the on-screen keyboard waits for a tap
  function drill(into: boolean): void {
    drillFocus.current = into ? '[data-menu-back]' : '[data-menu-filter]'
    setFilterOpen(into)
  }
  useLayoutEffect(() => {
    const menu = menuRef.current
    const trigger = triggerRef.current
    const target = drillFocus.current
    if (!target || !menu || !trigger) return
    drillFocus.current = null
    setPos(placeMenu(trigger, menu))
    menu.querySelector<HTMLElement>(target)?.focus()
  }, [filterOpen])

  useEffect(() => {
    if (!open) return
    return onMenuDismiss(
      () => [menuRef.current, triggerRef.current],
      () => {
        setOpen(false)
        setFilterOpen(false)
      },
    )
  }, [open])

  // The menu renders inside the draggable <th>: while open, dragging a control in it (the
  // filter's range slider) would drag the column instead
  useEffect(() => {
    const th = triggerRef.current?.closest('th')
    if (!open || !th) return
    th.draggable = false
    return () => {
      th.draggable = true
    }
  }, [open])

  function close(focusTrigger: boolean): void {
    setOpen(false)
    setFilterOpen(false)
    if (focusTrigger) triggerRef.current?.focus()
  }

  // Grouping or hiding can remove this header: focus the ▾ now at its position instead
  function act(item: Exclude<HeaderMenuItem, 'filter'>): void {
    const restoreFocus = triggerRef.current && keepHeaderMenuFocus(triggerRef.current)
    close(true)
    if (item === 'clear') onClearFilter()
    else if (item === 'group' || item === 'ungroup') onGroup()
    else onHide()
    if (restoreFocus) queueMicrotask(restoreFocus)
  }

  function onMenuKeyDown(e: KeyboardEvent<HTMLDivElement>): void {
    // Keys inside the filter flyout are the flyout's
    if ((e.target as Element).closest('[data-category-submenu], [data-menu-pane]')) return
    if (e.key === 'Escape') {
      e.preventDefault()
      close(true)
      return
    }
    const menu = menuRef.current
    if (!menu) return
    const focusables = ddNavFocusables(menu)
    const next = moveMenuIndex(
      e.key,
      focusables.indexOf(document.activeElement as HTMLElement),
      focusables.length,
    )
    if (next === null) return
    e.preventDefault()
    focusables[next]?.focus()
  }

  if (items.length === 0) return null
  return (
    <>
      <button
        type="button"
        data-col-menu
        ref={triggerRef}
        aria-label={label}
        aria-haspopup="dialog"
        aria-expanded={open}
        draggable={false}
        onClick={(e) => {
          e.stopPropagation()
          if (open) close(false)
          else setOpen(true)
        }}
        onMouseEnter={() => setLit(-1)}
        onMouseLeave={() => setLit(null)}
        style={{
          ...triggerStyle,
          ...(open || lit === -1 ? { background: hoverBg } : null),
          ...(filtered ? { color: 'var(--color-text-info)', fontWeight: 700 } : null),
        }}
      >
        {/* A funnel, not just a color, tells a filtered column apart */}
        {filtered ? <Icon item="filter" /> : '▾'}
      </button>
      {open && (
        <div
          ref={menuRef}
          role="dialog"
          aria-label={menuLabel}
          onClick={(e) => e.stopPropagation()}
          onKeyDown={onMenuKeyDown}
          onBlur={(e) => {
            // Focus leaving the panel closes it; a click inside may blur to nothing (null)
            const to = e.relatedTarget
            if (to && !e.currentTarget.contains(to) && to !== triggerRef.current) close(false)
          }}
          style={{ ...(drilled ? drilledPanelStyle : panelStyle), left: pos.left, top: pos.top }}
        >
          {drilled ? (
            <div
              data-menu-pane
              role="group"
              aria-label={L.filter}
              onKeyDown={(e) => {
                // ← in a text field moves its caret instead
                const inText = e.target instanceof HTMLInputElement && e.target.type !== 'checkbox'
                if (e.key !== 'Escape' && (e.key !== 'ArrowLeft' || inText)) return
                e.preventDefault()
                e.stopPropagation()
                drill(false)
              }}
              style={flyoutStyle}
            >
              <button
                type="button"
                data-menu-back
                onClick={() => drill(false)}
                onMouseEnter={() => setLit(-2)}
                onMouseLeave={() => setLit(null)}
                onFocus={() => setLit(-2)}
                onBlur={() => setLit(null)}
                style={{
                  ...itemStyle,
                  ...backStyle,
                  ...(lit === -2 ? { background: hoverBg } : null),
                }}
              >
                ‹ {column}
              </button>
              {filterPane}
            </div>
          ) : (
            items.map((item, i) =>
              item === 'filter' && narrow ? (
                <button
                  key={item}
                  type="button"
                  data-dd-row
                  data-menu-filter
                  onClick={() => drill(true)}
                  onKeyDown={(e) => e.key === 'ArrowRight' && drill(true)}
                  onMouseEnter={() => setLit(i)}
                  onMouseLeave={() => setLit(null)}
                  onFocus={() => setLit(i)}
                  onBlur={() => setLit(null)}
                  style={lit === i ? { ...itemStyle, background: hoverBg } : itemStyle}
                >
                  <Icon item={item} />
                  <span style={{ flex: 1 }}>{L[HEADER_MENU_ITEMS[item].label]}</span>
                  <span style={arrowStyle}>▸</span>
                </button>
              ) : item === 'filter' ? (
                <CategorySubmenu
                  key={item}
                  name={L[HEADER_MENU_ITEMS[item].label]}
                  icon={<Icon item={item} />}
                  groupLabel={L[HEADER_MENU_ITEMS[item].label]}
                  panelStyle={flyoutStyle}
                  isOpen={filterOpen}
                  onOpen={() => setFilterOpen(true)}
                  onClose={() => setFilterOpen(false)}
                >
                  {filterPane}
                </CategorySubmenu>
              ) : (
                <button
                  key={item}
                  type="button"
                  data-dd-row
                  onClick={() => act(item)}
                  onMouseEnter={() => setLit(i)}
                  onMouseLeave={() => setLit(null)}
                  onFocus={() => setLit(i)}
                  onBlur={() => setLit(null)}
                  style={lit === i ? { ...itemStyle, background: hoverBg } : itemStyle}
                >
                  <Icon item={item} />
                  {L[HEADER_MENU_ITEMS[item].label]}
                </button>
              ),
            )
          )}
        </div>
      )}
    </>
  )
}
