// packages/solid/src/components/FilterPane.tsx
import { For, Show, createEffect, createMemo, createSignal } from 'solid-js'
import type { ValueSort } from '@vates/data-table-core'
import {
  computeStringValueCounts,
  filterValuesBySearch,
  filterValuesByCount,
  filterValuesByRange,
  computeValueBounds,
  sortFilterValues,
  cycleValueSort,
  toggleSortDir,
  getValueSortIcon,
  getDateSortIcon,
  computeDateTree,
  isMultiValueColumn,
  computeVirtualRange,
  getVirtualScrollTarget,
  checklistBulkState,
  clickChecklistValue,
  clickDateTreeNode,
  toggleChecklistValues,
  type DateTreeNode,
  applyCheckboxState,
  deferCheckboxCorrection,
} from '@vates/data-table-core/internal'
import type { TableState } from '../createTableState'
import type { ColumnDef } from '../types'
import { RangeInputs } from './RangeInputs'
import { DateTreeItem } from './DateTreeItem'

interface FilterPaneProps<TRow extends object> {
  table: TableState<TRow>
  col: ColumnDef<TRow>
}

const DEFAULT_VALUE_SORT: ValueSort = { by: 'alpha', dir: 'asc' }
// Checklist virtualization (see "Checklist virtualization" below): a fixed per-row height so the
// windowing math is exact, and an assumed viewport height safe because `.dt-filter-panel`'s own
// `max-height: 380px` bounds how much taller the checklist can ever grow past this default —
// comfortably inside the 5-row/160px overscan `computeVirtualRange` already renders each side, so
// the mounted window always covers the real visible box. Matches React/Vue's own constants.
const FILTER_LIST_ITEM_HEIGHT = 32
const FILTER_LIST_VIEWPORT_HEIGHT = 260

interface FilterSearchRowProps {
  checked: boolean
  selectAllLabel: string
  onSelectAll: () => void
  checkboxRef: (el: HTMLInputElement) => void
  searchPlaceholder: string
  searchValue: string
  onSearchInput: (value: string) => void
  sortIcon: string
  sortLabel: string
  onSortClick: () => void
  // Any/all match-mode control — only meaningful for a genuinely array-valued column (see
  // `isMultiValueColumn`), so the caller passes these only when that's the case; omitted
  // entirely (rather than always rendered and disabled) for a plain scalar column, where
  // "match all selected values" could never match more than one value at a time anyway.
  // Rendered as two buttons rather than one cycling button — see FilterDropdown's own comment
  // on `matchMode`/`onSetMatchMode` for why "Any"/"All" both need to be visible, equal-weight
  // options rather than one being a default/passive non-state.
  matchMode?: 'and' | 'or'
  matchAnyLabel?: string
  matchAllLabel?: string
  onSetMatchMode?: (mode: 'and' | 'or') => void
  clearSearchLabel: string
}

// Select-all checkbox + value search input + sort-order toggle — shared by the string checklist
// and the date tree (the date branch had been missing this entirely at first; see docs/filter-dropdown.md's
// "Filter dropdown" section). Both narrow/select over the same filterDetailValues() pipeline
// regardless of which control (checklist or tree) renders those values, so this row's own
// behavior is identical either way — only the sort icon function differs (alpha/count vs.
// chronological), passed in by the caller.
function FilterSearchRow(props: FilterSearchRowProps) {
  return (
    <div class="dt-filter-search-row">
      <input
        type="checkbox"
        title={props.selectAllLabel}
        aria-label={props.selectAllLabel}
        checked={props.checked}
        ref={props.checkboxRef}
        onClick={props.onSelectAll}
      />
      <span class="dt-dd-search-wrap">
        <input
          type="text"
          class="dt-dd-search"
          data-dd-value-search
          placeholder={props.searchPlaceholder}
          value={props.searchValue}
          onInput={(e) => props.onSearchInput(e.currentTarget.value)}
        />
        <Show when={props.searchValue}>
          <button
            type="button"
            class="dt-dd-search-clear"
            title={props.clearSearchLabel}
            aria-label={props.clearSearchLabel}
            onClick={() => props.onSearchInput('')}
          >
            ×
          </button>
        </Show>
      </span>
      <button
        type="button"
        class="dt-value-sort-btn"
        title={props.sortLabel}
        aria-label={props.sortLabel}
        onClick={props.onSortClick}
      >
        {props.sortIcon}
      </button>
      <Show when={props.matchMode}>
        <div class="dt-filter-match-mode-group" role="group">
          <button
            type="button"
            class={`dt-value-sort-btn dt-filter-match-mode dt-filter-match-mode--left${props.matchMode === 'or' ? ' dt-filter-match-mode--active' : ''}`}
            title={props.matchAnyLabel}
            aria-label={props.matchAnyLabel}
            aria-pressed={props.matchMode === 'or'}
            onClick={() => props.onSetMatchMode?.('or')}
          >
            {props.matchAnyLabel}
          </button>
          <button
            type="button"
            class={`dt-value-sort-btn dt-filter-match-mode dt-filter-match-mode--right${props.matchMode === 'and' ? ' dt-filter-match-mode--active' : ''}`}
            title={props.matchAllLabel}
            aria-label={props.matchAllLabel}
            aria-pressed={props.matchMode === 'and'}
            onClick={() => props.onSetMatchMode?.('and')}
          >
            {props.matchAllLabel}
          </button>
        </div>
      </Show>
    </div>
  )
}

const multiValueCache = new WeakMap<object[], Map<string, boolean>>()

/** The pane's keyboard stops, in order: value search, then checklist rows or date tree checkboxes */
export function detailFocusables(detailEl: Element): HTMLElement[] {
  return Array.from(
    detailEl.querySelectorAll<HTMLElement>(
      'input[data-dd-value-search], input[data-dd-value-row], .dt-date-tree-wrap input[type="checkbox"]',
    ),
  )
}

// One column's filter controls — checklist (string, virtualized — see "Checklist virtualization"
// below), range + slider (number), or a Year›Month›Day tree + range + slider (date). Shown by the
// Filter dropdown's right pane and the header menu's Filter flyout; its view state (value search,
// value order, shift-click anchor, expanded date nodes) lives here, so render it keyed by column.
export function FilterPane<TRow extends object>(props: FilterPaneProps<TRow>) {
  const { table } = props
  const activeCol = () => props.col
  const col = activeCol
  const [searchTerm, setSearchTerm] = createSignal('')
  const [valueSort, setValueSort] = createSignal<ValueSort>(
    props.col.defaultValueSort ?? DEFAULT_VALUE_SORT,
  )
  const [anchorValue, setAnchor] = createSignal<string>()
  const [expanded, setExpanded] = createSignal(new Set<string>())

  // Scoped via targetKeys to just the active column — see docs/performance.md's "Performance": computing
  // this for every filterable column on every change is the single biggest cost this library has
  // measured (~15-17x at 500k rows), and only one column's checklist is ever shown at a time.
  const stringValueCounts = createMemo(() => {
    const col = activeCol()
    return (
      computeStringValueCounts(
        table.data(),
        table.filter.include(),
        table.filter.ranges(),
        table.columns.list(),
        table.labels().emptyValue,
        [col.key],
        table.filter.exclude(),
        table.filter.modes(),
      )[col.key] ?? new Map()
    )
  })

  const bounds = createMemo(() => {
    const col = activeCol()
    return computeValueBounds(table.data(), col)
  })

  // Any/all match mode — only surfaced in the UI for a column whose values are actually
  // array-shaped in the data (see `isMultiValueColumn`'s own doc comment for why a plain scalar
  // column has no meaningful "all" mode to switch to).
  //
  // Cached per data array and column key (module-level, since a pane is recreated per column):
  // revisiting a column otherwise reruns a full O(rows) scan, which never short-circuits for a
  // scalar column. Multi-valueness is a property of the data shape, stable while `data` is.
  const isMultiValueCol = createMemo(() => {
    const col = activeCol()
    const data = table.data()
    let byKey = multiValueCache.get(data)
    if (!byKey) multiValueCache.set(data, (byKey = new Map()))
    let cached = byKey.get(col.key)
    if (cached === undefined) {
      cached = isMultiValueColumn(data, col, col.key)
      byKey.set(col.key, cached)
    }
    return cached
  })
  const matchMode = createMemo(() => {
    const col = activeCol()
    return table.filter.modes()[col.key] ?? col.multiMode ?? 'or'
  })

  // A non-multi-value column's checklist uses a checked-by-default, exclude-only model instead
  // of the tri-state include/exclude cycle (see docs/filter-dropdown.md's "Filter dropdown"): `filters` is
  // never written for such a column, "checked" simply means "not in `excludeFilters`". Date/
  // number columns (their own detail branches below) and genuinely multi-value columns keep the
  // original include-based model untouched.
  const usesExcludeOnly = createMemo(() => {
    const col = activeCol()
    if (col.type === 'date' || col.type === 'number') return false
    return !isMultiValueCol()
  })

  // The set a value must be in to stay visible even at a 0 facet count (see
  // `filterValuesByCount`) — whichever map the active column's model actually writes to.
  function alreadyTouched(col: ColumnDef<TRow>): Set<string> {
    return usesExcludeOnly()
      ? (table.filter.exclude()[col.key] ?? new Set())
      : (table.filter.include()[col.key] ?? new Set())
  }

  // Count/range-filtered, but *not* yet narrowed by the checklist's own value search — kept
  // separate from filterDetailValues below so `otherValues` can diff the two to find exactly what
  // the search is currently hiding. Order relative to search doesn't matter here: range/count
  // filtering and search are independent per-value predicates, so computing them in either order
  // yields the same final set.
  const detailValuesBeforeSearch = createMemo(() => {
    const col = activeCol()
    let values = table.filter.valueMap()[col.key] ?? []
    if (col.type === 'date')
      values = filterValuesByRange(values, table.filter.ranges()[col.key], col.parseDate)
    return filterValuesByCount(values, stringValueCounts(), alreadyTouched(col))
  })

  const filterDetailValues = createMemo(() => {
    const col = activeCol()
    const values = filterValuesBySearch(detailValuesBeforeSearch(), searchTerm())
    return sortFilterValues(values, stringValueCounts(), valueSort(), col.compare)
  })

  // "Others" — the values the checklist's own value search is currently hiding (see docs/filter-dropdown.md's
  // "Filter dropdown"). Only meaningful once a search term actually narrows the list; empty
  // otherwise, which also keeps it a no-op for the date tree's own (unused) reference to this.
  const otherValues = createMemo(() => {
    if (!searchTerm()) return []
    const shown = new Set(filterDetailValues())
    return detailValuesBeforeSearch().filter((v) => !shown.has(v))
  })

  const dateTree = createMemo(() => {
    const col = activeCol()
    if (col.type !== 'date') return []
    return computeDateTree(
      filterDetailValues(),
      table.labels().emptyValue,
      valueSort().dir,
      col.parseDate,
    )
  })

  // --- Checklist virtualization ---
  // A column with thousands of distinct values (a customer name, an order ID) would otherwise
  // mount one <label>/<input> per value regardless of scroll position — see docs/performance.md's
  // "Performance" and "The flat checklist is virtualized in React and Vue" in the docs. Solid's
  // own version of this, windowing filterDetailValues() the same way.
  let filterListEl: HTMLDivElement | undefined
  const [scrollTop, setScrollTop] = createSignal(0)
  // Resets scroll to 0 whenever the active column or its search term changes — matches React/
  // Vue's own reset trigger (a stale scroll position from a previous column/search makes no
  // sense against a freshly-narrowed list).
  createEffect(() => {
    void searchTerm()
    setScrollTop(0)
    if (filterListEl) filterListEl.scrollTop = 0
  })
  const filterListVirtualRange = createMemo(() =>
    computeVirtualRange(
      scrollTop(),
      FILTER_LIST_VIEWPORT_HEIGHT,
      FILTER_LIST_ITEM_HEIGHT,
      filterDetailValues().length,
    ),
  )

  function toggleExpand(path: string): void {
    setExpanded((prev) => {
      const next = new Set(prev)
      if (next.has(path)) next.delete(path)
      else next.add(path)
      return next
    })
  }
  function cycleSort(): void {
    const col = activeCol()
    setValueSort(
      col.type === 'date'
        ? { ...valueSort(), dir: toggleSortDir(valueSort().dir) }
        : cycleValueSort(valueSort()),
    )
  }

  // --- Flat checklist (string columns), "Others" and date tree: shared click logic in core ---
  const touched = () =>
    (usesExcludeOnly() ? table.filter.exclude() : table.filter.include())[activeCol().key]
  function handleValueClick(value: string, shiftKey: boolean): void {
    clickChecklistValue(table.filter, activeCol().key, value, shiftKey, {
      anchor: anchorValue(),
      values: filterDetailValues(),
      include: table.filter.include()[activeCol().key],
      exclude: table.filter.exclude()[activeCol().key],
      excludeOnly: usesExcludeOnly(),
    })
    setAnchor(value)
  }
  function handleSelectAll(): void {
    toggleChecklistValues(table.filter, activeCol().key, filterDetailValues(), usesExcludeOnly())
    // No preventDefault() here (this checkbox is a plain two-state toggle, not tri-state), but
    // the native pre-click activation can still race Solid's own synchronous write on rare
    // event-ordering — deferring a correction alongside the state update is cheap insurance.
    deferCheckboxCorrection(selectAllEl, () => selectAllState())
  }
  const selectAllState = createMemo(() =>
    checklistBulkState(filterDetailValues(), touched(), usesExcludeOnly()),
  )
  let selectAllEl: HTMLInputElement | undefined
  createEffect(() => {
    applyCheckboxState(selectAllEl, selectAllState().checked, selectAllState().indeterminate)
  })

  function handleOthersToggle(): void {
    toggleChecklistValues(table.filter, activeCol().key, otherValues(), usesExcludeOnly())
    deferCheckboxCorrection(othersEl, () => othersState())
  }
  const othersState = createMemo(() =>
    checklistBulkState(otherValues(), touched(), usesExcludeOnly()),
  )
  let othersEl: HTMLInputElement | undefined
  createEffect(() => {
    applyCheckboxState(othersEl, othersState().checked, othersState().indeterminate)
  })

  function handleDateNodeToggle(node: DateTreeNode, shiftKey: boolean): void {
    clickDateTreeNode(table.filter, activeCol().key, node, shiftKey, {
      anchorPath: anchorValue(),
      tree: dateTree(),
      values: filterDetailValues(),
      include: table.filter.include()[activeCol().key],
      parseDate: activeCol().parseDate,
    })
    setAnchor(node.path)
  }

  // --- Row nav (Up/Down/Home/End); Escape clears a non-empty value search first ---
  function handleKeyDown(e: KeyboardEvent): void {
    if (e.key === 'Escape' && searchTerm()) {
      e.preventDefault()
      e.stopPropagation()
      setSearchTerm('')
      // Clearing can remove the focused element (the "Others" row): keep focus on the search box
      ;(e.currentTarget as HTMLElement)
        .querySelector<HTMLElement>('input[data-dd-value-search]')
        ?.focus()
      return
    }
    if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp' && e.key !== 'Home' && e.key !== 'End') return

    // The flat checklist is virtualized (see "Checklist virtualization" below) — only a
    // scrolled-into-view window of rows actually exists in the DOM, so Up/Down/Home/End need to
    // reach a *logical* value that isn't necessarily mounted, via filterDetailValues() (the full
    // narrowed list) rather than a DOM query. Falls through to the generic DOM-order nav below in
    // two cases, same as React/Vue's own version: moving Up out of the very first row (there's no
    // row above it — the previous stop is the search box instead, itself always mounted so plain
    // DOM order already gets there), and starting from the search box itself (ArrowDown to row 0
    // is likewise always mounted). The date tree has no such window, so it always uses the
    // generic path.
    const col = activeCol()
    if (col.type !== 'date' && col.type !== 'number') {
      const values = filterDetailValues()
      const active = document.activeElement
      const activeValue =
        active instanceof HTMLInputElement && active.matches('input[data-dd-value-row]')
          ? active.dataset.value
          : undefined
      let targetIdx: number | null = null
      if (e.key === 'Home') targetIdx = 0
      else if (e.key === 'End') targetIdx = values.length - 1
      else if (activeValue !== undefined) {
        const curIdx = values.indexOf(activeValue)
        targetIdx = e.key === 'ArrowDown' ? curIdx + 1 : curIdx - 1
      }
      if (targetIdx !== null) {
        const fallsThrough = targetIdx < 0 && e.key === 'ArrowUp' && activeValue !== undefined
        if (!fallsThrough) {
          if (targetIdx < 0 || targetIdx >= values.length) {
            e.preventDefault()
            return
          }
          e.preventDefault()
          focusChecklistIndex(targetIdx, values)
          return
        }
      }
    }

    const focusables = detailFocusables(e.currentTarget as HTMLElement)
    const active = document.activeElement as HTMLElement | null
    const idx = active ? focusables.indexOf(active) : -1
    if (idx === -1) return
    if (e.key === 'Home' || e.key === 'End') {
      const rowFocusables = focusables.filter((el) => !el.matches('input[data-dd-value-search]'))
      if (rowFocusables.length === 0) return
      e.preventDefault()
      ;(e.key === 'Home' ? rowFocusables[0] : rowFocusables[rowFocusables.length - 1]).focus()
      return
    }
    const nextIdx = e.key === 'ArrowDown' ? idx + 1 : idx - 1
    if (nextIdx < 0 || nextIdx >= focusables.length) return
    e.preventDefault()
    focusables[nextIdx].focus()
  }

  // Scrolls (if needed) and focuses the checklist row at `values[targetIdx]` — the scroll-then-
  // focus dance a virtualized list needs when the target isn't in the currently-mounted window.
  // Solid's DOM update for the new window is synchronous within this same call (same reasoning
  // as the Sort/Group activate/remove focus retention elsewhere in this codebase), so no
  // pending-ref/effect indirection is needed: set scrollTop, then focus, in the same tick.
  function focusChecklistIndex(targetIdx: number, values: string[]): void {
    const value = values[targetIdx]
    const nextScrollTop = getVirtualScrollTarget(
      scrollTop(),
      FILTER_LIST_VIEWPORT_HEIGHT,
      FILTER_LIST_ITEM_HEIGHT,
      targetIdx,
    )
    if (nextScrollTop !== null) {
      if (filterListEl) filterListEl.scrollTop = nextScrollTop
      setScrollTop(nextScrollTop)
    }
    if (!filterListEl) return
    for (const cb of filterListEl.querySelectorAll<HTMLInputElement>('input[data-dd-value-row]')) {
      if (cb.dataset.value === value) {
        cb.focus()
        break
      }
    }
  }

  return (
    <div class="dt-filter-detail" onKeyDown={handleKeyDown}>
      <Show
        when={col().type === 'number'}
        fallback={
          <Show
            when={col().type === 'date'}
            fallback={
              // --- String checklist ---
              <>
                <FilterSearchRow
                  checked={selectAllState().checked}
                  selectAllLabel={table.labels().selectAll}
                  onSelectAll={handleSelectAll}
                  checkboxRef={(el) => (selectAllEl = el)}
                  searchPlaceholder={table.labels().filterSearchPlaceholder}
                  searchValue={searchTerm()}
                  onSearchInput={setSearchTerm}
                  sortIcon={getValueSortIcon(valueSort())}
                  sortLabel={table.labels().sortValues}
                  onSortClick={cycleSort}
                  matchMode={isMultiValueCol() ? matchMode() : undefined}
                  matchAnyLabel={table.labels().filterMatchAny}
                  matchAllLabel={table.labels().filterMatchAll}
                  onSetMatchMode={(mode) => table.filter.setMode(col().key, mode)}
                  clearSearchLabel={table.labels().clearSearch}
                />
                {/* Bulk (de)select everything the value search above is currently hiding
                        — see docs/filter-dropdown.md's "Filter dropdown". Only rendered once a search term
                        actually narrows the list. */}
                <Show when={otherValues().length > 0}>
                  <label class="dt-dd-item dt-filter-others">
                    <input
                      type="checkbox"
                      title={table.labels().filterOthers}
                      aria-label={table.labels().filterOthers}
                      checked={othersState().checked}
                      ref={othersEl}
                      onClick={(e) => {
                        e.preventDefault()
                        handleOthersToggle()
                      }}
                    />
                    <span class="dt-flex1">{table.labels().filterOthers}</span>
                    <span class="dt-filter-count" aria-hidden="true">
                      {otherValues().length}
                    </span>
                  </label>
                </Show>
                <div
                  class="dt-filter-list"
                  ref={filterListEl}
                  onScroll={(e) => setScrollTop(e.currentTarget.scrollTop)}
                >
                  {/* Spacer sized to the *full* (unwindowed) list so the real scrollbar
                          still reports the true item count's size; the inner div positions
                          just the mounted window at its real offset within that spacer. */}
                  <div
                    style={{
                      height: `${filterListVirtualRange().totalHeight}px`,
                      position: 'relative',
                    }}
                  >
                    <div
                      style={{
                        position: 'absolute',
                        top: `${filterListVirtualRange().offsetY}px`,
                        left: 0,
                        right: 0,
                      }}
                    >
                      <For
                        each={filterDetailValues().slice(
                          filterListVirtualRange().startIndex,
                          filterListVirtualRange().endIndex,
                        )}
                      >
                        {(value) => {
                          // Non-multi-value column: plain checked/unchecked, "checked"
                          // meaning "not excluded" — no tri-state indeterminate cue.
                          // Multi-value column: unchanged include/exclude tri-state,
                          // shown as checked/indeterminate.
                          const checked = () =>
                            usesExcludeOnly()
                              ? !(table.filter.exclude()[col().key]?.has(value) ?? false)
                              : (table.filter.include()[col().key]?.has(value) ?? false)
                          const indeterminate = () =>
                            usesExcludeOnly()
                              ? false
                              : (table.filter.exclude()[col().key]?.has(value) ?? false)
                          // Explains each model's own click behavior — the checked-by-
                          // default model has no tri-state cycle to describe, so it gets
                          // its own plain hide/show copy instead of reusing the tri-state
                          // labels (see docs/filter-dropdown.md's "Filter dropdown").
                          const itemTitle = () =>
                            usesExcludeOnly()
                              ? checked()
                                ? table.labels().filterValueHideTitle
                                : table.labels().filterValueShowTitle
                              : indeterminate()
                                ? table.labels().filterExcludedTitle
                                : table.labels().filterValueTitle
                          const count = () => stringValueCounts().get(value) ?? 0
                          let el: HTMLInputElement | undefined
                          createEffect(() => {
                            applyCheckboxState(el, checked(), indeterminate())
                          })
                          return (
                            <label
                              class="dt-dd-item"
                              style={{
                                height: `${FILTER_LIST_ITEM_HEIGHT}px`,
                                'box-sizing': 'border-box',
                              }}
                            >
                              <input
                                type="checkbox"
                                data-dd-value-row
                                data-value={value}
                                checked={checked()}
                                title={itemTitle()}
                                ref={el}
                                onClick={(e) => {
                                  e.preventDefault()
                                  handleValueClick(value, (e as MouseEvent).shiftKey)
                                  deferCheckboxCorrection(el, () => ({
                                    checked: checked(),
                                    indeterminate: indeterminate(),
                                  }))
                                }}
                              />
                              <span class="dt-flex1">
                                {col().renderFilterLabel ? col().renderFilterLabel!(value) : value}
                              </span>
                              <span class="dt-filter-count" aria-hidden="true">
                                {count()}
                              </span>
                            </label>
                          )
                        }}
                      </For>
                    </div>
                  </div>
                </div>
              </>
            }
          >
            {/* --- Date tree --- */}
            <RangeInputs
              col={col()}
              rangeFilter={table.filter.ranges()[col().key]}
              bounds={bounds()}
              minLabel={table.labels().min}
              maxLabel={table.labels().max}
              onChange={(kind, value) => table.filter.setRange(col().key, kind, value)}
              onSliderCommit={(min, max) => {
                table.filter.setRange(col().key, 'min', min)
                table.filter.setRange(col().key, 'max', max)
              }}
            />
            <FilterSearchRow
              checked={selectAllState().checked}
              selectAllLabel={table.labels().selectAll}
              onSelectAll={handleSelectAll}
              checkboxRef={(el) => (selectAllEl = el)}
              searchPlaceholder={table.labels().filterSearchPlaceholder}
              searchValue={searchTerm()}
              onSearchInput={setSearchTerm}
              sortIcon={getDateSortIcon(valueSort().dir)}
              sortLabel={table.labels().sortValues}
              onSortClick={cycleSort}
              clearSearchLabel={table.labels().clearSearch}
            />
            <div class="dt-date-tree-wrap">
              <For each={dateTree()}>
                {(node) => (
                  <DateTreeItem
                    node={node}
                    depth={0}
                    selected={table.filter.include()[col().key] ?? new Set()}
                    counts={stringValueCounts()}
                    expanded={expanded()}
                    searchActive={searchTerm() !== ''}
                    onToggleExpand={toggleExpand}
                    onToggleNode={handleDateNodeToggle}
                  />
                )}
              </For>
            </div>
          </Show>
        }
      >
        {/* --- Number range --- */}
        <RangeInputs
          col={col()}
          rangeFilter={table.filter.ranges()[col().key]}
          bounds={bounds()}
          minLabel={table.labels().min}
          maxLabel={table.labels().max}
          onChange={(kind, value) => table.filter.setRange(col().key, kind, value)}
          onSliderCommit={(min, max) => {
            table.filter.setRange(col().key, 'min', min)
            table.filter.setRange(col().key, 'max', max)
          }}
        />
      </Show>
    </div>
  )
}

// packages/vue/src/components/FilterPane.vue
<script lang="ts">
// Per data array and column key: revisiting a column (panes are recreated per column) otherwise
// reruns a full O(rows) scan, which never short-circuits for a scalar column. Multi-valueness is a
// property of the data shape, stable while `data` is.
const multiValueCache = new WeakMap<object[], Map<string, boolean>>()
</script>

<script setup lang="ts" generic="TRow extends object">
import { computed, nextTick, ref, watch } from 'vue'
import {
  computeStringValueCounts,
  isMultiValueColumn,
  filterValuesBySearch,
  filterValuesByCount,
  filterValuesByRange,
  computeValueBounds,
  computeRangeSliderGeometry,
  formatRangeBound,
  sortFilterValues,
  cycleValueSort,
  toggleSortDir,
  getValueSortIcon,
  getDateSortIcon,
  computeDateTree,
  checklistBulkState,
  clickChecklistValue,
  clickDateTreeNode,
  toggleChecklistValues,
  deferCheckboxCorrection,
  computeVirtualRange,
  getVirtualScrollTarget,
  type DateTreeNode,
} from '@vates/data-table-core/internal'
import type { ValueSort } from '@vates/data-table-core'
import type { ColumnDef } from '../types'
import type { TableState } from '../useTableState'
import DateTreeItem from './DateTreeItem.vue'
import RangeInputs from './RangeInputs.vue'
import { vIndeterminate } from '../directives/vIndeterminate'

// One column's filter controls — checklist (string, virtualized), range + slider (number), or a
// Year›Month›Day tree + range + slider (date). Shown by the Filter dropdown's right pane and the
// header menu's Filter flyout; its view state (value search, value order, shift-click anchor,
// expanded date nodes) lives here, so render it keyed by column. Styled by DataTableView.vue's
// `:deep()` rules, like the rest of the Filter dropdown.
const props = defineProps<{
  table: TableState<TRow>
  col: ColumnDef<TRow>
  data: TRow[]
  columns: ColumnDef<TRow>[]
}>()
defineSlots<{ value?: (props: { value: string }) => unknown }>()

const DEFAULT_VALUE_SORT: ValueSort = { by: 'alpha', dir: 'asc' }
// Fixed row height so the windowing math is exact; the assumed viewport height is safe because
// the pane's own max-height bounds how much taller the list can grow past it, well inside
// computeVirtualRange's overscan. Matches React/Solid's constants.
const FILTER_LIST_ITEM_HEIGHT = 32
const FILTER_LIST_VIEWPORT_HEIGHT = 260

const L = props.table.labels
const {
  include: filters,
  exclude: excludeFilters,
  ranges: rangeFilters,
  modes: filterModes,
  valueMap: stringValueMap,
  setMode: setFilterMode,
  setRange: setRangeFilter,
} = props.table.filter

const searchTerm = ref('')
const valueSort = ref<ValueSort>(props.col.defaultValueSort ?? DEFAULT_VALUE_SORT)
const anchor = ref<string | null>(null)
const expanded = ref(new Set<string>())

// Scoped to this one column (computeStringValueCounts's targetKeys) — computing it for every
// filterable column is this library's single biggest measured cost.
const valueCounts = computed(
  () =>
    computeStringValueCounts(
      props.data,
      filters.value,
      rangeFilters.value,
      props.columns,
      L.value.emptyValue,
      [props.col.key],
      excludeFilters.value,
      filterModes.value,
    )[props.col.key] ?? new Map<string, number>(),
)

// Any/all match mode — only for a column whose values are actually arrays (see
// isMultiValueColumn), and only for the string checklist.
const isMultiValue = computed(() => {
  const col = props.col
  if (col.type === 'date' || col.type === 'number') return false
  let byKey = multiValueCache.get(props.data)
  if (!byKey) multiValueCache.set(props.data, (byKey = new Map()))
  let cached = byKey.get(col.key)
  if (cached === undefined) {
    cached = isMultiValueColumn(props.data, col, col.key)
    byKey.set(col.key, cached)
  }
  return cached
})
// A non-multi-value string column uses a checked-by-default, exclude-only model (see
// docs/filter-dropdown.md's "Filter dropdown"): "checked" means "not in `excludeFilters`".
const usesExcludeOnly = computed(
  () => props.col.type !== 'date' && props.col.type !== 'number' && !isMultiValue.value,
)
const matchMode = computed(() => filterModes.value[props.col.key] ?? props.col.multiMode ?? 'or')

// The set a value must be in to stay visible even at a 0 facet count (see filterValuesByCount).
const alreadyTouched = computed(() =>
  usesExcludeOnly.value
    ? (excludeFilters.value[props.col.key] ?? new Set<string>())
    : (filters.value[props.col.key] ?? new Set<string>()),
)
// Range/count-filtered, not yet narrowed by the value search — `otherValues` diffs the two.
const beforeSearchValues = computed(() =>
  filterValuesByCount(
    filterValuesByRange(
      stringValueMap.value[props.col.key] ?? [],
      rangeFilters.value[props.col.key],
      props.col.parseDate,
    ),
    valueCounts.value,
    alreadyTouched.value,
  ),
)
const values = computed(() =>
  sortFilterValues(
    filterValuesBySearch(beforeSearchValues.value, searchTerm.value),
    valueCounts.value,
    valueSort.value,
    props.col.compare,
  ),
)
// "Others": the values the value search is hiding; empty without a search.
const otherValues = computed(() => {
  if (!searchTerm.value) return []
  const shown = new Set(values.value)
  return beforeSearchValues.value.filter((v) => !shown.has(v))
})

function isValueChecked(value: string): boolean {
  return usesExcludeOnly.value
    ? !(excludeFilters.value[props.col.key]?.has(value) ?? false)
    : (filters.value[props.col.key]?.has(value) ?? false)
}
function isValueExcluded(value: string): boolean {
  return usesExcludeOnly.value ? false : (excludeFilters.value[props.col.key]?.has(value) ?? false)
}
function valueTitle(value: string): string {
  if (usesExcludeOnly.value)
    return isValueChecked(value) ? L.value.filterValueHideTitle : L.value.filterValueShowTitle
  return isValueExcluded(value) ? L.value.filterExcludedTitle : L.value.filterValueTitle
}

// Select-all and "Others" state and clicks: shared logic in core
const touched = () => (usesExcludeOnly.value ? excludeFilters.value : filters.value)[props.col.key]
const allState = computed(() => checklistBulkState(values.value, touched(), usesExcludeOnly.value))
const othersState = computed(() =>
  checklistBulkState(otherValues.value, touched(), usesExcludeOnly.value),
)
function toggleAllOf(vals: string[]): void {
  toggleChecklistValues(props.table.filter, props.col.key, vals, usesExcludeOnly.value)
}
function onOthersClick(event: MouseEvent): void {
  event.preventDefault()
  toggleAllOf(otherValues.value)
  deferCheckboxCorrection(event.currentTarget as HTMLInputElement, () => othersState.value)
}

function onValueClick(value: string, event: MouseEvent): void {
  // Vue's `:checked` only rewrites the DOM property when the bound value changes, so the native
  // toggle is prevented and the binding alone drives the checkbox (see the tri-state cycle) — but
  // the browser reverts a prevented click after Vue's write, hence the deferred correction.
  event.preventDefault()
  deferCheckboxCorrection(event.currentTarget as HTMLInputElement, () => ({
    checked: isValueChecked(value),
    indeterminate: isValueExcluded(value),
  }))
  clickChecklistValue(props.table.filter, props.col.key, value, event.shiftKey, {
    anchor: anchor.value,
    values: values.value,
    include: filters.value[props.col.key],
    exclude: excludeFilters.value[props.col.key],
    excludeOnly: usesExcludeOnly.value,
  })
  anchor.value = value
}

function cycleSort(): void {
  valueSort.value =
    props.col.type === 'date'
      ? { ...valueSort.value, dir: toggleSortDir(valueSort.value.dir) }
      : cycleValueSort(valueSort.value)
}

// Bounds over the full, unfiltered data so the slider doesn't shift under a mid-drag user.
const bounds = computed(() =>
  props.col.type === 'number' || props.col.type === 'date'
    ? computeValueBounds(props.data, props.col)
    : null,
)
const slider = computed(() => {
  const b = bounds.value
  if (!b || b.min >= b.max) return null
  const geo = computeRangeSliderGeometry(
    rangeFilters.value[props.col.key],
    b,
    props.col.type === 'date',
  )
  return { min: b.min, max: b.max, low: geo.low, high: geo.high, step: geo.step }
})
function rangeValue(kind: 'min' | 'max'): string {
  return (
    rangeFilters.value[props.col.key]?.[kind] ??
    (bounds.value ? formatRangeBound(bounds.value[kind], props.col) : '')
  )
}
function onSliderChange(low: number, high: number): void {
  setRangeFilter(props.col.key, 'min', formatRangeBound(low, props.col))
  setRangeFilter(props.col.key, 'max', formatRangeBound(high, props.col))
}

const dateTree = computed(() =>
  props.col.type === 'date'
    ? computeDateTree(values.value, L.value.emptyValue, valueSort.value.dir, props.col.parseDate)
    : [],
)
function toggleExpand(path: string): void {
  const next = new Set(expanded.value)
  if (next.has(path)) next.delete(path)
  else next.add(path)
  expanded.value = next
}
function onDateNodeClick(node: DateTreeNode, event: MouseEvent): void {
  clickDateTreeNode(props.table.filter, props.col.key, node, event.shiftKey, {
    anchorPath: anchor.value,
    tree: dateTree.value,
    values: values.value,
    include: filters.value[props.col.key],
    parseDate: props.col.parseDate,
  })
  anchor.value = node.path
}

// --- Checklist virtualization ---
const scrollTop = ref(0)
const listRef = ref<HTMLElement | null>(null)
let rafPending = false
function onListScroll(): void {
  if (rafPending) return
  rafPending = true
  requestAnimationFrame(() => {
    rafPending = false
    if (listRef.value) scrollTop.value = listRef.value.scrollTop
  })
}
// A narrower list makes the old scroll position meaningless
watch(searchTerm, () => {
  scrollTop.value = 0
  if (listRef.value) listRef.value.scrollTop = 0
})
const virtualRange = computed(() =>
  computeVirtualRange(
    scrollTop.value,
    FILTER_LIST_VIEWPORT_HEIGHT,
    FILTER_LIST_ITEM_HEIGHT,
    values.value.length,
  ),
)

// --- Row nav (Up/Down/Home/End); Escape clears a non-empty value search first ---
async function onKeydown(event: KeyboardEvent): Promise<void> {
  if (event.key === 'Escape' && searchTerm.value) {
    event.preventDefault()
    event.stopPropagation()
    searchTerm.value = ''
    // Clearing can remove the focused element (the "Others" row): keep focus on the search box
    const pane = event.currentTarget as HTMLElement
    await nextTick()
    pane.querySelector<HTMLElement>('input.dt__dd-search')?.focus()
    return
  }
  if (event.altKey || !['ArrowDown', 'ArrowUp', 'Home', 'End'].includes(event.key)) return
  const pane = event.currentTarget as HTMLElement
  // Only the value search joins the vertical chain; select-all and the sort button sit beside it
  const headerControls = Array.from(pane.querySelectorAll<HTMLElement>('input.dt__dd-search'))
  const rowInputs = Array.from(
    pane.querySelectorAll<HTMLInputElement>(
      '.dt__dd-item input[type="checkbox"], .dt__date-tree-item input[type="checkbox"]',
    ),
  )
  const focusables = [...headerControls, ...rowInputs]
  const active = document.activeElement as HTMLElement | null
  if (!active || focusables.indexOf(active) === -1) return

  // The flat checklist is virtualized: reaching a logical row outside the mounted window (or
  // Home/End) scrolls first, then focuses once Vue re-renders the window.
  const checklistEl = pane.querySelector<HTMLElement>('.dt__filter-list')
  if (checklistEl) {
    const vals = values.value
    const activeValue =
      active instanceof HTMLInputElement && rowInputs.includes(active)
        ? active.dataset.value
        : undefined
    let targetIdx: number | null = null
    if (event.key === 'Home') targetIdx = 0
    else if (event.key === 'End') targetIdx = vals.length - 1
    else if (activeValue !== undefined) {
      const curIdx = vals.indexOf(activeValue)
      targetIdx = event.key === 'ArrowDown' ? curIdx + 1 : curIdx - 1
    }
    // Up out of the first row falls through to the plain nav below, back to the search box
    if (targetIdx !== null && !(targetIdx < 0 && event.key === 'ArrowUp' && activeValue)) {
      event.preventDefault()
      if (targetIdx < 0 || targetIdx >= vals.length) return
      const next =
        getVirtualScrollTarget(
          scrollTop.value,
          FILTER_LIST_VIEWPORT_HEIGHT,
          FILTER_LIST_ITEM_HEIGHT,
          targetIdx,
        ) ?? scrollTop.value
      scrollTop.value = next
      if (listRef.value) listRef.value.scrollTop = next
      const targetValue = vals[targetIdx]
      await nextTick()
      for (const cb of checklistEl.querySelectorAll<HTMLInputElement>('input[type="checkbox"]')) {
        if (cb.dataset.value === targetValue) {
          cb.focus()
          break
        }
      }
      return
    }
  }

  if (event.key === 'Home' || event.key === 'End') {
    if (rowInputs.length === 0) return
    event.preventDefault()
    ;(event.key === 'Home' ? rowInputs[0] : rowInputs[rowInputs.length - 1]).focus()
    return
  }
  const nextIdx = focusables.indexOf(active) + (event.key === 'ArrowDown' ? 1 : -1)
  if (nextIdx < 0 || nextIdx >= focusables.length) return
  event.preventDefault()
  focusables[nextIdx].focus()
}
</script>

<template>
  <div class="dt__filter-detail" data-filter-detail @keydown="onKeydown">
    <RangeInputs
      v-if="col.type === 'number' || col.type === 'date'"
      :is-date="col.type === 'date'"
      :min="rangeValue('min')"
      :max="rangeValue('max')"
      :min-label="L.min"
      :max-label="L.max"
      :slider="slider"
      @update:min="setRangeFilter(col.key, 'min', $event)"
      @update:max="setRangeFilter(col.key, 'max', $event)"
      @slider-change="onSliderChange"
    />
    <template v-if="col.type !== 'number'">
      <div class="dt__filter-search-row">
        <input
          v-if="values.length > 0"
          v-indeterminate="allState.indeterminate"
          type="checkbox"
          class="dt__filter-select-all"
          :checked="allState.checked"
          :title="L.selectAll"
          :aria-label="L.selectAll"
          @change="toggleAllOf(values)"
        />
        <span class="dt__dd-search-wrap">
          <input
            v-model="searchTerm"
            type="text"
            class="dt__dd-search"
            data-dd-value-search
            :placeholder="L.filterSearchPlaceholder"
          />
          <button
            v-if="searchTerm"
            type="button"
            class="dt__dd-search-clear"
            :title="L.clearSearch"
            :aria-label="L.clearSearch"
            @click="searchTerm = ''"
          >
            ×
          </button>
        </span>
        <button
          type="button"
          class="dt__value-sort-btn"
          :title="L.sortValues"
          :aria-label="L.sortValues"
          @click="cycleSort"
        >
          {{ col.type === 'date' ? getDateSortIcon(valueSort.dir) : getValueSortIcon(valueSort) }}
        </button>
        <div v-if="isMultiValue" class="dt__filter-match-mode-group" role="group">
          <button
            type="button"
            class="dt__value-sort-btn dt__filter-match-mode dt__filter-match-mode--left"
            :class="{ 'dt__filter-match-mode--active': matchMode === 'or' }"
            :title="L.filterMatchAny"
            :aria-label="L.filterMatchAny"
            :aria-pressed="matchMode === 'or'"
            @click="setFilterMode(col.key, 'or')"
          >
            {{ L.filterMatchAny }}
          </button>
          <button
            type="button"
            class="dt__value-sort-btn dt__filter-match-mode dt__filter-match-mode--right"
            :class="{ 'dt__filter-match-mode--active': matchMode === 'and' }"
            :title="L.filterMatchAll"
            :aria-label="L.filterMatchAll"
            :aria-pressed="matchMode === 'and'"
            @click="setFilterMode(col.key, 'and')"
          >
            {{ L.filterMatchAll }}
          </button>
        </div>
      </div>
      <div v-if="col.type === 'date'" class="dt__date-tree-wrap">
        <DateTreeItem
          :nodes="dateTree"
          :depth="0"
          :selected="filters[col.key] ?? new Set()"
          :counts="valueCounts"
          :expanded="expanded"
          :search-active="searchTerm !== ''"
          @toggle-node="onDateNodeClick"
          @toggle-expand="toggleExpand"
        />
      </div>
      <template v-else>
        <!-- Bulk (de)select what the value search is hiding; only shown while it hides something -->
        <label v-if="otherValues.length > 0" class="dt__dd-item dt__filter-others">
          <input
            v-indeterminate="othersState.indeterminate"
            type="checkbox"
            :title="L.filterOthers"
            :aria-label="L.filterOthers"
            :checked="othersState.checked"
            @click="onOthersClick"
          />
          <span class="dt__flex1">{{ L.filterOthers }}</span>
          <span class="dt__filter-count">{{ otherValues.length }}</span>
        </label>
        <!-- Virtualized: only rows scrolled into view (+ overscan) are mounted -->
        <div ref="listRef" class="dt__filter-list" @scroll="onListScroll">
          <div :style="{ height: virtualRange.totalHeight + 'px', position: 'relative' }">
            <div
              :style="{ position: 'absolute', top: virtualRange.offsetY + 'px', left: 0, right: 0 }"
            >
              <label
                v-for="v in values.slice(virtualRange.startIndex, virtualRange.endIndex)"
                :key="v"
                class="dt__dd-item dt__dd-item--clickable"
                :class="{ 'dt__dd-item--exclude': isValueExcluded(v) }"
                :style="{ height: FILTER_LIST_ITEM_HEIGHT + 'px', boxSizing: 'border-box' }"
              >
                <!-- Tri-state for a multi-value column (indeterminate = excluded), plain
                     checked/unchecked otherwise; v-indeterminate sets the DOM property -->
                <input
                  v-indeterminate="isValueExcluded(v)"
                  type="checkbox"
                  data-dd-value-row
                  :data-value="v"
                  :checked="isValueChecked(v)"
                  :title="valueTitle(v)"
                  @click="onValueClick(v, $event)"
                />
                <span class="dt__flex1">
                  <slot name="value" :value="v">{{ v }}</slot>
                </span>
                <span class="dt__filter-count">{{ valueCounts.get(v) ?? 0 }}</span>
              </label>
            </div>
          </div>
        </div>
      </template>
    </template>
  </div>
</template>
