// packages/solid/src/components/HeaderMenu.tsx
import { For, Show, createSignal, onCleanup } from 'solid-js'
import {
  FILTER_NARROW_QUERY,
  HEADER_MENU_ITEMS,
  columnHasActiveFilter,
  ddNavFocusables,
  getHeaderMenuItems,
  keepHeaderMenuFocus,
  moveMenuIndex,
  onMenuDismiss,
  placeMenu,
  watchMedia,
  type HeaderMenuItem,
} from '@vates/data-table-core/internal'
import type { ColumnDef } from '../types'
import type { TableState } from '../createTableState'
import { CategorySubmenu } from './CategorySubmenu'
import { FilterPane } from './FilterPane'

interface HeaderMenuProps<TRow extends object> {
  table: TableState<TRow>
  col: ColumnDef<TRow>
  onOpenChange: (open: boolean) => void
}

function Icon(props: { item: HeaderMenuItem }) {
  return (
    <svg
      class="dt-th-menu-icon"
      viewBox="0 0 16 16"
      fill="none"
      stroke="currentColor"
      stroke-width="1.5"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <path d={HEADER_MENU_ITEMS[props.item].icon} />
    </svg>
  )
}

const FILTER_KINDS = ['include', 'exclude', 'range'] as const

// A header's ▾ menu. `position: fixed` (like CategorySubmenu) so the table's scrolling wrapper
// doesn't clip it; it closes on any scroll rather than tracking its header.
export function HeaderMenu<TRow extends object>(props: HeaderMenuProps<TRow>) {
  const { table } = props
  const [open, setOpen] = createSignal(false)
  const [filterOpen, setFilterOpen] = createSignal(false)
  const [pos, setPos] = createSignal({ left: 0, top: 0 })
  let triggerRef: HTMLButtonElement | undefined
  let menuRef: HTMLDivElement | undefined
  let stopDismiss: (() => void) | undefined

  const key = () => props.col.key
  const isFiltered = () =>
    columnHasActiveFilter(
      key(),
      table.filter.include(),
      table.filter.exclude(),
      table.filter.ranges(),
    )
  const items = () =>
    getHeaderMenuItems(props.col, table.group.by(), table.columns.active().length, isFiltered())
  const label = (item: HeaderMenuItem) => table.labels()[HEADER_MENU_ITEMS[item].label]
  // No room for a flyout beside the menu: Filter swaps the panel's items for its pane instead
  const [narrow, setNarrow] = createSignal(false)
  onCleanup(watchMedia(FILTER_NARROW_QUERY, setNarrow))
  const drilled = () => narrow() && filterOpen()

  onCleanup(() => {
    stopDismiss?.()
    if (open()) props.onOpenChange(false)
  })

  function openMenu(): void {
    setOpen(true)
    props.onOpenChange(true)
    stopDismiss = onMenuDismiss(
      () => [menuRef, triggerRef],
      () => close(false),
    )
    queueMicrotask(() => {
      if (!menuRef || !triggerRef) return
      setPos(placeMenu(triggerRef, menuRef))
      ddNavFocusables(menuRef)[0]?.focus()
    })
  }
  function close(focusTrigger: boolean): void {
    setOpen(false)
    props.onOpenChange(false)
    setFilterOpen(false)
    stopDismiss?.()
    if (focusTrigger) triggerRef?.focus()
  }

  // Focuses the back row rather than the search box, so the on-screen keyboard waits for a tap
  function drill(into: boolean): void {
    setFilterOpen(into)
    queueMicrotask(() => {
      if (!menuRef || !triggerRef) return
      setPos(placeMenu(triggerRef, menuRef))
      menuRef.querySelector<HTMLElement>(into ? '[data-menu-back]' : '[data-menu-filter]')?.focus()
    })
  }

  // Grouping or hiding can remove this header: focus the ▾ now at its position instead
  function act(item: Exclude<HeaderMenuItem, 'filter'>): void {
    const restoreFocus = triggerRef && keepHeaderMenuFocus(triggerRef)
    close(true)
    if (item === 'clear') for (const kind of FILTER_KINDS) table.filter.clearColumn(key(), kind)
    else if (item === 'group' || item === 'ungroup') table.group.toggle(key())
    else table.columns.toggleVisibility(key())
    if (restoreFocus) queueMicrotask(restoreFocus)
  }

  function onMenuKeyDown(e: KeyboardEvent): void {
    // Keys inside the filter flyout are the flyout's
    if ((e.target as Element).closest('.dt-th-filter-flyout')) return
    if (e.key === 'Escape') {
      e.preventDefault()
      close(true)
      return
    }
    if (!menuRef) return
    const focusables = ddNavFocusables(menuRef)
    const next = moveMenuIndex(
      e.key,
      focusables.indexOf(document.activeElement as HTMLElement),
      focusables.length,
    )
    if (next === null) return
    e.preventDefault()
    focusables[next]?.focus()
  }

  return (
    <Show when={items().length > 0}>
      <button
        type="button"
        class="dt-th-menu"
        classList={{ 'dt-th-menu--filtered': isFiltered() }}
        data-col-menu
        ref={triggerRef}
        aria-label={table.labels().columnMenu(props.col.label, isFiltered())}
        aria-haspopup="dialog"
        aria-expanded={open()}
        draggable={false}
        onClick={(e) => {
          e.stopPropagation()
          if (open()) close(false)
          else openMenu()
        }}
      >
        {/* A funnel, not just a color, tells a filtered column apart */}
        <Show when={isFiltered()} fallback="▾">
          <Icon item="filter" />
        </Show>
      </button>
      <Show when={open()}>
        <div
          class="dt-dd-submenu dt-th-menu-panel"
          classList={{ 'dt-th-menu-panel--drilled': drilled() }}
          role="dialog"
          aria-label={table.labels().columnMenu(props.col.label, false)}
          ref={menuRef}
          style={{ position: 'fixed', left: `${pos().left}px`, top: `${pos().top}px` }}
          onClick={(e) => e.stopPropagation()}
          onKeyDown={onMenuKeyDown}
          onFocusOut={(e) => {
            // Focus leaving the panel closes it; a click inside may blur to nothing (null)
            const to = e.relatedTarget as Node | null
            if (to && !menuRef?.contains(to) && to !== triggerRef) close(false)
          }}
        >
          <Show
            when={drilled()}
            fallback={
              <For each={items()}>
                {(item) =>
                  item === 'filter' && narrow() ? (
                    <button
                      type="button"
                      class="dt-dd-item dt-dd-item--click"
                      data-dd-row
                      data-menu-filter
                      onClick={() => drill(true)}
                      onKeyDown={(e) => e.key === 'ArrowRight' && drill(true)}
                    >
                      <Icon item={item} />
                      <span class="dt-flex1">{label(item)}</span>
                      <span class="dt-dd-category-arrow">▸</span>
                    </button>
                  ) : item === 'filter' ? (
                    <CategorySubmenu
                      name={label(item)}
                      icon={<Icon item={item} />}
                      groupLabel={label(item)}
                      class="dt-th-filter-flyout"
                      isOpen={filterOpen()}
                      onOpen={() => setFilterOpen(true)}
                      onClose={() => setFilterOpen(false)}
                    >
                      <FilterPane table={table} col={props.col} />
                    </CategorySubmenu>
                  ) : (
                    <button
                      type="button"
                      class="dt-dd-item dt-dd-item--click"
                      data-dd-row
                      onClick={() => act(item)}
                    >
                      <Icon item={item} />
                      {label(item)}
                    </button>
                  )
                }
              </For>
            }
          >
            <div
              class="dt-th-filter-flyout"
              role="group"
              aria-label={label('filter')}
              onKeyDown={(e) => {
                // ← in a text field moves its caret instead
                const inText = e.target instanceof HTMLInputElement && e.target.type !== 'checkbox'
                if (e.key !== 'Escape' && (e.key !== 'ArrowLeft' || inText)) return
                e.preventDefault()
                e.stopPropagation()
                drill(false)
              }}
            >
              <button
                type="button"
                class="dt-dd-item dt-dd-item--click dt-filter-back"
                data-menu-back
                onClick={() => drill(false)}
              >
                ‹ {props.col.label}
              </button>
              <FilterPane table={table} col={props.col} />
            </div>
          </Show>
        </div>
      </Show>
    </Show>
  )
}

// packages/vue/src/components/HeaderMenu.vue
<script setup lang="ts" generic="TRow extends object">
import { computed, nextTick, onUnmounted, ref } from 'vue'
import {
  FILTER_NARROW_QUERY,
  HEADER_MENU_ITEMS,
  columnHasActiveFilter,
  ddNavFocusables,
  getHeaderMenuItems,
  keepHeaderMenuFocus,
  moveMenuIndex,
  onMenuDismiss,
  placeMenu,
  watchMedia,
  type HeaderMenuItem,
} from '@vates/data-table-core/internal'
import type { ColumnDef } from '../types'
import type { TableState } from '../useTableState'
import CategorySubmenu from './CategorySubmenu.vue'
import FilterPane from './FilterPane.vue'

// A header's ▾ menu. `position: fixed` (like CategorySubmenu) so the table's scrolling wrapper
// doesn't clip it; it closes on any scroll rather than tracking its header.
const props = defineProps<{
  table: TableState<TRow>
  col: ColumnDef<TRow>
  data: TRow[]
  columns: ColumnDef<TRow>[]
}>()
const emit = defineEmits<{ openChange: [open: boolean] }>()
// `value`: the filter flyout's value label, forwarded to FilterPane
// `label`: the value through the column's `format`, the default content
defineSlots<{ value?: (props: { value: string; label: string }) => unknown }>()

const ROW_SELECTOR = 'button.dt__dd-item--clickable'

const open = ref(false)
const filterOpen = ref(false)
const pos = ref({ left: 0, top: 0 })
const triggerRef = ref<HTMLButtonElement | null>(null)
const menuRef = ref<HTMLDivElement | null>(null)
let stopDismiss: (() => void) | undefined
// No room for a flyout beside the menu: Filter swaps the panel's items for its pane instead
const narrow = ref(false)
const stopWatch = watchMedia(FILTER_NARROW_QUERY, (m) => (narrow.value = m))
const drilled = computed(() => narrow.value && filterOpen.value)

const L = props.table.labels
const items = computed(() =>
  getHeaderMenuItems(
    props.col,
    props.table.group.by.value,
    props.table.columns.active.value.length,
    isFiltered.value,
  ),
)
const isFiltered = computed(() =>
  columnHasActiveFilter(
    props.col.key,
    props.table.filter.include.value,
    props.table.filter.exclude.value,
    props.table.filter.ranges.value,
  ),
)

onUnmounted(() => {
  stopWatch()
  stopDismiss?.()
  if (open.value) emit('openChange', false)
})

async function openMenu(): Promise<void> {
  open.value = true
  emit('openChange', true)
  stopDismiss = onMenuDismiss(
    () => [menuRef.value, triggerRef.value],
    () => close(false),
  )
  await nextTick()
  if (!menuRef.value || !triggerRef.value) return
  pos.value = placeMenu(triggerRef.value, menuRef.value)
  ddNavFocusables(menuRef.value, ROW_SELECTOR)[0]?.focus()
}
function close(focusTrigger: boolean): void {
  open.value = false
  filterOpen.value = false
  emit('openChange', false)
  stopDismiss?.()
  if (focusTrigger) triggerRef.value?.focus()
}

// Focuses the back row rather than the search box, so the on-screen keyboard waits for a tap
async function drill(into: boolean): Promise<void> {
  filterOpen.value = into
  await nextTick()
  if (!menuRef.value || !triggerRef.value) return
  pos.value = placeMenu(triggerRef.value, menuRef.value)
  menuRef.value
    .querySelector<HTMLElement>(into ? '[data-menu-back]' : '[data-menu-filter]')
    ?.focus()
}
function onPaneKeydown(e: KeyboardEvent): void {
  // ← in a text field moves its caret instead
  const inText = e.target instanceof HTMLInputElement && e.target.type !== 'checkbox'
  if (e.key !== 'Escape' && (e.key !== 'ArrowLeft' || inText)) return
  e.preventDefault()
  e.stopPropagation()
  void drill(false)
}

// Grouping or hiding can remove this header: focus the ▾ now at its position instead
function act(item: Exclude<HeaderMenuItem, 'filter'>): void {
  const restoreFocus = triggerRef.value && keepHeaderMenuFocus(triggerRef.value)
  close(true)
  if (item === 'clear')
    for (const kind of ['include', 'exclude', 'range'] as const)
      props.table.filter.clearColumn(props.col.key, kind)
  else if (item === 'group' || item === 'ungroup') props.table.group.toggle(props.col.key)
  else props.table.columns.toggleVisibility(props.col.key)
  if (restoreFocus) void nextTick(restoreFocus)
}

// Focus leaving the panel closes it; a click inside may blur to nothing (null)
function onMenuFocusout(e: FocusEvent): void {
  const to = e.relatedTarget as Node | null
  if (to && !menuRef.value?.contains(to) && to !== triggerRef.value) close(false)
}

function onMenuKeydown(e: KeyboardEvent): void {
  // Keys inside the filter flyout are the flyout's
  if ((e.target as Element).closest('.dt__th-filter-flyout')) return
  if (e.key === 'Escape') {
    e.preventDefault()
    close(true)
    return
  }
  if (!menuRef.value) return
  const rows = ddNavFocusables(menuRef.value, ROW_SELECTOR)
  const next = moveMenuIndex(
    e.key,
    rows.indexOf(document.activeElement as HTMLElement),
    rows.length,
  )
  if (next === null) return
  e.preventDefault()
  rows[next]?.focus()
}
</script>

<template>
  <template v-if="items.length > 0">
    <button
      ref="triggerRef"
      type="button"
      class="dt__th-menu"
      :class="{ 'dt__th-menu--filtered': isFiltered }"
      data-col-menu
      :aria-label="L.columnMenu(col.label, isFiltered)"
      aria-haspopup="dialog"
      :aria-expanded="open"
      draggable="false"
      @click.stop="open ? close(false) : openMenu()"
    >
      <!-- A funnel, not just a color, tells a filtered column apart -->
      <svg
        v-if="isFiltered"
        class="dt__th-menu-icon"
        viewBox="0 0 16 16"
        fill="none"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linejoin="round"
        aria-hidden="true"
      >
        <path :d="HEADER_MENU_ITEMS.filter.icon" />
      </svg>
      <template v-else>▾</template>
    </button>
    <div
      v-if="open"
      ref="menuRef"
      class="dt__dd-submenu dt__th-menu-panel"
      :class="{ 'dt__th-menu-panel--drilled': drilled }"
      role="dialog"
      :aria-label="L.columnMenu(col.label, false)"
      :style="{ position: 'fixed', left: `${pos.left}px`, top: `${pos.top}px` }"
      @click.stop
      @keydown="onMenuKeydown"
      @focusout="onMenuFocusout"
    >
      <div
        v-if="drilled"
        class="dt__th-filter-flyout"
        role="group"
        :aria-label="L.filter"
        @keydown="onPaneKeydown"
      >
        <button
          type="button"
          class="dt__dd-item dt__dd-item--clickable dt__th-menu-back"
          data-menu-back
          @click="drill(false)"
        >
          ‹ {{ col.label }}
        </button>
        <FilterPane :table="table" :col="col" :data="data" :columns="columns">
          <template #value="{ value, label }"
            ><slot name="value" :value="value" :label="label"
          /></template>
        </FilterPane>
      </div>
      <template v-else>
        <template v-for="item in items" :key="item">
          <button
            v-if="item === 'filter' && narrow"
            type="button"
            class="dt__dd-item dt__dd-item--clickable"
            data-menu-filter
            @click="drill(true)"
            @keydown.right="drill(true)"
          >
            <svg
              class="dt__th-menu-icon"
              viewBox="0 0 16 16"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path :d="HEADER_MENU_ITEMS[item].icon" />
            </svg>
            <span class="dt__th-menu-label">{{ L[HEADER_MENU_ITEMS[item].label] }}</span>
            <span class="dt__th-menu-arrow">▸</span>
          </button>
          <CategorySubmenu
            v-else-if="item === 'filter'"
            :name="L[HEADER_MENU_ITEMS[item].label]"
            :group-label="L[HEADER_MENU_ITEMS[item].label]"
            submenu-class="dt__th-filter-flyout"
            :is-open="filterOpen"
            @open="filterOpen = true"
            @close="filterOpen = false"
          >
            <template #icon>
              <svg
                class="dt__th-menu-icon"
                viewBox="0 0 16 16"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linejoin="round"
                aria-hidden="true"
              >
                <path :d="HEADER_MENU_ITEMS[item].icon" />
              </svg>
            </template>
            <FilterPane :table="table" :col="col" :data="data" :columns="columns">
              <template #value="{ value, label }"
                ><slot name="value" :value="value" :label="label"
              /></template>
            </FilterPane>
          </CategorySubmenu>
          <button
            v-else
            type="button"
            class="dt__dd-item dt__dd-item--clickable"
            @click="act(item)"
          >
            <svg
              class="dt__th-menu-icon"
              viewBox="0 0 16 16"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path :d="HEADER_MENU_ITEMS[item].icon" />
            </svg>
            {{ L[HEADER_MENU_ITEMS[item].label] }}
          </button>
        </template>
      </template>
    </div>
  </template>
</template>

<style scoped>
.dt__th-menu {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  width: 24px;
  height: 24px;
  margin: -4px 0 -4px auto;
  padding: 0;
  border: none;
  border-radius: 4px;
  background: none;
  color: var(--color-text-secondary);
  font: inherit;
  cursor: pointer;
}
.dt__th-menu:hover,
.dt__th-menu[aria-expanded='true'] {
  background: var(--color-background-secondary);
}
.dt__th-menu--filtered {
  color: var(--color-text-info);
  font-weight: 700;
}
.dt__dd-submenu {
  z-index: 101;
  background: var(--color-background-primary);
  border: 0.5px solid var(--color-border-secondary);
  border-radius: 8px;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
  min-width: 160px;
  max-height: 320px;
  overflow-y: auto;
  padding: 4px 0;
  font-weight: 400;
}
.dt__dd-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 7px 14px;
  font-size: 13px;
  color: var(--color-text-primary);
  border: none;
  background: none;
  font-family: inherit;
  text-align: left;
  margin: 0;
  width: 100%;
  box-sizing: border-box;
}
.dt__dd-item--clickable {
  cursor: pointer;
}
.dt__dd-item--clickable:hover,
.dt__dd-item--clickable:focus {
  background: var(--color-background-secondary);
}
/* The icon in the Filter item sits in CategorySubmenu's trigger, the flyout in its template */
:deep(.dt__th-menu-icon),
.dt__th-menu-icon {
  width: 14px;
  height: 14px;
  flex-shrink: 0;
}
.dt__th-menu-panel {
  /* 100vw counts a classic scrollbar too, hence more than twice the 8 px viewport margin */
  max-width: calc(100vw - 40px);
}
/* Holds the filter pane itself, which scrolls its own list */
.dt__th-menu-panel--drilled {
  max-height: none;
  overflow: hidden;
  padding: 0;
}
.dt__th-menu-back {
  flex-shrink: 0;
  font-weight: 500;
  border-bottom: 0.5px solid var(--color-border-tertiary);
}
.dt__th-menu-label {
  flex: 1;
}
.dt__th-menu-arrow {
  flex-shrink: 0;
  font-size: 10px;
  color: var(--color-text-tertiary);
}
.dt__th-filter-flyout,
:deep(.dt__dd-submenu.dt__th-filter-flyout) {
  display: flex;
  flex-direction: column;
  max-height: 380px;
  overflow: hidden;
  padding: 0;
}
</style>
